### ISSUE TITLE
Setup automatic publishing

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#10]
Automatically build and publish tags to `plugins.gradle.org`

**Comment by bsautel** [comment]
I created in a branch a new Github Actions workflow that published the plugin when a new tag is pushed. I cannot test it, hope it will work.

It requires to define the publication key and secret in the Github project secrets, here are their names:
- `PLUGIN_PORTAL_KEY`
- `PLUGIN_PORTAL_SECRET`

Note that we also could create a release, but it requires the release notes to be defined in the workflow file before each release. What do you think about that @deepy?

**Comment by deepy** [comment]
Secrets have been added, good job 👍 

The big downside to the plugin portal is that we can't publish snapshots, so at some point in the future we might have to add bintray or something similar

**Comment by bsautel** [comment]
Ok, thanks for the secrets.

And what about publishing alpha or beta versions to the plugin portal? Is this possible?

**Comment by deepy** [comment]
The plugin portal considers everything you publish to be a release, if you push `1.2.3-SNAPSHOT` that's not being treated as a `SNAPSHOT` so you can't republish it and you only have 7 days to remove it (which we shouldn't do), if `semver-git` lets us there's nothing preventing us from pushing RCs though, but if we are to publish pre-release versions we should probably set up bintray.

**Comment by deepy** [comment]
Had to try this locally, but `3.0.0-rc1` shows up correctly in `showVersion` and jar names

**Comment by bsautel** [comment]
Ok, so we can do some RC versions with the `semver-git` plugin. But as discussed in #102, we probably want to publish all releases and snapshots to bintray.

**Comment by deepy** [comment]
So apparently the way it works is that anything that is requested from the plugin portal and doesn't exist is redirect to bintray, which means means that we can publish snapshots, at least to people using the legacy version of applying plugins.

**Comment by bsautel** [comment]
@deepy , I prepared the release of the 2.2.4 version but the automatic publication does not work.

There is a authorization issue that we can see [here](https://github.com/node-gradle/gradle-node-plugin/runs/684545483?check_suite_focus=true).

There is also a version issue. I pushed a tag 2.2.4 that triggered the publication but the version seems to be 0.1.0-SNAPSHOT. Did you do anything else before publication when you released manually?

**Comment by deepy** [comment]
@bsautel is 2.2.4 an annotated tag? `git tag -a`, if it's publishing `0.1.0-SNAPSHOT` that might be why the publication fails (as there's already an `0.1.0-SNAPSHOT`).

But otherwise as long as git is available semver-git should be able to resolve the version

**Comment by deepy** [comment]
2.2.4 seems to be a lightweight tag and not an annotated tag, I'll recreate it and see if that solves it.

**Comment by bsautel** [comment]
It was probably not an annotated tag, I created it via IntelliJ. I did not know that I has to be an annotated tag.

And you are right, the unauthorized error can come from this issue.

I created the tag, the build is running. 🤞

Thanks for your quick answer!

**Comment by deepy** [comment]
It's kinda sad that lightweight tags are the default in git, they are by most definitions pretty terrible but their biggest crime is how they lack information on when they were created and by who.

But on the bright side, now we have a good candidate for a `CONTRIBUTING.md` _and_ we got the instructions and a documentation on the failure in an issue :-)

**Comment by deepy** [comment]
Why do all CIs nowadays insist on keeping the git history away from you :p?

I'm looking at the current failure.

**Comment by deepy** [comment]
I published 2.2.4 manually, couldn't find a quick way to disable `--no-tags` in the GitHub action's fetch

**Comment by bsautel** [comment]
Ok, thanks.  Good job!

So that confirms that the authorization issue was related to the wrong version.

I saw in the GitHub checkout action documentation [how to checkout tags](https://github.com/marketplace/actions/checkout#Fetch-all-tags). We probably should add that line to the publication workflow, shouldn't we?

**Comment by bsautel** [comment]
I added an action to the GitHub publish workflow to checkout tags. Hope this will work! 🤞
