### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by iherasymenko** [node-gradle/gradle-node-plugin#104]
First of all, thank you for this fork. 

Is there a chance to have a new release published to the gradle repo?

I'm particularly interested in this issue. https://github.com/node-gradle/gradle-node-plugin/issues/96

**Comment by bsautel** [comment]
I think we are ready to release the 2.2.4 version. @deepy, what do you think about that?

**Comment by deepy** [comment]
Sounds good to me, and we'll get a chance to try out the github publishing action too :-)

**Comment by iherasymenko** [comment]
Thanks! I would also love to try out a 3.x.x snapshot build if there were a way :)

**Comment by bsautel** [comment]
I tried to publish the 2.2.4 version but the automatic publication does not work( it's the first time we run it, we could not test it before). I added some details in issue #10.

Regarding a snapshot of the version 3, we are also working on that (#62, #102, #79). It should be available soon.

**Comment by deepy** [comment]
@iherasymenko I've published 2.2.4 manually, GitHub Actions is misbehaving

**Comment by bsautel** [comment]
I close the issue. See #62 for snapshots publication.

**Comment by iherasymenko** [comment]
@deepy @bsautel thank you 🙇‍♂️
