### ISSUE TITLE
Changing the Registry for NPM/Yarn

### ISSUE THREAD

**Issue by clarencejychan** [node-gradle/gradle-node-plugin#107]
I'm currently using node-gradle plugin but my company requires that even a distribution of Yarn/NPM need to come from the company's artifactory. I managed to get the version of node from my companies artifactory but I'm having a lot of trouble trying to set up the NPM/Yarn to download from the artficatory. 

I've tried doing things like 
```
afterEvaluate() {
    println 'http://company/artifactory/api/npm/npm-external-new/'
    yarnSetup.args += ['--registry=company/artifactory/api/npm/npm-external-new/']
    println yarnSetup.args
  }
```

but it still defaults to
```
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/yarn failed,
```

Is there any way I can get around this?

**Comment by clarencejychan** [comment]
I also tried setting the NPM registry since the Node installation comes with NPM and probably uses NPM to install Yarn..

**Comment by deepy** [comment]
Which task produces the error?
It looks like your `afterEvaluate` should work, so I'm wondering if the error is from `npmSetup`

**Comment by rcsilva83** [comment]
It worked for me. Thanks!

**Comment by deepy** [comment]
In case anyone wants to change registry in yet another way, you can add `NPM_CONFIG_REGISTRY` to the environment
