### ISSUE TITLE
.gradle/nodejs/node-v12.13.0-linux-x64/bin/npm'' finished with non-zero exit value 127

### ISSUE THREAD

**Issue by jsong8** [node-gradle/gradle-node-plugin#110]
Running a gradle build gives errors:

nodeSetup UP-TO-DATE
:npmSetup SKIPPED
:npmInstallenv: ‘node’: No such file or directory
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':uiAdmin:npmInstall'.
> Process 'command '/var/jenkins_home/workspace/.../.gradle/nodejs/node-v12.13.0-linux-x64/bin/npm'' finished with non-zero exit value 127

Here is the build file.

plugins {
  id "java"
  id "com.github.node-gradle.node" version "2.2.4"
}
node {
    version = "12.13.0"
    download = true
}
npm_run_build {
  args = ['--prod', '--env=prod']
}

jar.dependsOn 'npm_run_build'

**Comment by jsong8** [comment]
The build file does work locally on my laptop. So this is not an issue of the plugin. Sorry if I post the question on the wrong place.

**Comment by deepy** [comment]
It's kinda strange that `nodeSetup` would say it's `UP-TO-DATE` and node not existing, but if you're using `musl` that might be it, are you using Alpine Linux or building in docker?
If so there's #51 in regards to that
