### ISSUE TITLE
Add support for Gradle configuration cache

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#111]
https://github.com/gradle/gradle/issues/13490

Gradle 6.6 is introducing configuration caching

Helpful resources 
- https://medium.com/androiddevelopers/configuration-caching-deep-dive-bcb304698070
- https://docs.gradle.org/nightly/userguide/configuration_cache.html
- https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- https://docs.gradle.org/nightly/userguide/custom_gradle_types.html#service_injection

**Comment by deepy** [comment]
I think we might have to drop support for older versions of gradle for this

**Comment by deepy** [comment]
Which would put 2/3 of our users at Gradle 5 or earlier

**Comment by deepy** [comment]
Version | Users | Percentage
-- | -- | --
Gradle 6 | 998 | 72.11%
Gradle 5 | 327 | 23.63%
Gradle 4 | 29 | 2.10%
Gradle 3 | 26 | 1.88%
Gradle 2 | 4 | 0.29%
Total | 1,384 | 100%

**Comment by eskatos** [comment]
It depends (famous answer :) ). With the configuration cache, some things are unsupported, but you can still branch depending on the current Gradle version to provide support.

Looking at the numbers above, targeting Gradle >= 5 .0 could be considered but even with that there are APIs that are only available in >6.x and branching per Gradle version would be mandatory here and there anyway 🤷 

The plugin is quite different but this PR https://github.com/michel-kraemer/gradle-download-task/pull/157 made the Download task compatible with the configuration cache without loosing compatibility with Gradle >=2.0.

**Comment by deepy** [comment]
Thank you so much for the information @eskatos!

The dance performed in `ProjectApiHelper` is pretty much exactly what we need :-)

I'll see if I can get a branch going this week

**Comment by deepy** [comment]
Started working on the branch `2.x-configuration-cache`

Everything worked fine up until I switched from `project.exec`, I think everything is working but we just need to change `mockExec` in the tests.
https://github.com/node-gradle/gradle-node-plugin/blob/2.2.4/src/test/groovy/com/moowork/gradle/node/task/AbstractTaskTest.groovy#L33

**Comment by eskatos** [comment]
Sounds good!

To make sure the support is complete I would make sure that there's at least tests that runs builds with the configuration cache enabled, reusing the cached state, for a clean build, i.e. running all tasks after skipping the configuration phase. In other words, with build cache disabled and configuration cache enabled, run once to store the cache then clean and then run again reusing the cache.

**Comment by deepy** [comment]
Having looked some at this and tested on an example project I think we can make this work pretty easily on 2.x for the `download = false` cases.

**Comment by eskatos** [comment]
What's up with `download = true`? If you point me to the related part of the code I could take a look

**Comment by deepy** [comment]
We're adding the repository for downloading node/npm/yarn in the tasks' action, something which would probably be pretty easy to fix but moving it would change functionality enough to be a major change, and the next major is planned to be the kotlin rewrite so my idea is to see how far I can take the `2.x` branch, then do the same on `master` and then finalise the support on `master`

**Comment by eskatos** [comment]
Hi @deepy,
Any news on a first cut of the support?

**Comment by deepy** [comment]
Hi @eskatos, unfortunately there were some more things that needed to be fixed in 2.x before this could be added and they're already done on master, so we'll have to do it after 3.x is released.
The release of which was delayed a bit by my dog getting sick and my laptop being in the wrong town, but when 3.x is released this is the top priority.

**Comment by eskatos** [comment]
Thanks for your quick answer. Sounds good

Hope your dog is fine now! :dog:

**Comment by deepy** [comment]
I've begun working on this and while I get the integration tests to work all the unit tests fails to capture the invocation of execSpec: [NpmInstallTaskTest.groovy#L15](https://github.com/node-gradle/gradle-node-plugin/blob/3.0.0-rc4/src/test/groovy/com/github/gradle/node/npm/task/NpmInstallTaskTest.groovy#L15)

The mock and spy is setup like this: [AbstractTaskTest.groovy#L31-L45](https://github.com/node-gradle/gradle-node-plugin/blob/3.0.0-rc4/src/test/groovy/com/github/gradle/node/task/AbstractTaskTest.groovy#L31-L45) and while this works fine with project I can't get this same pattern to work with `ExecOperations`. 
I tried the same pattern but can't find anything to hook onto, I tried retrieving the `DefaultProjectApiHelper` and changing the `execOperations` through metaprogramming but with no results.

On the bright side, the only integration tests are failing right now are the proxy related ones and I think that might be this laptop.

**Comment by bsautel** [comment]
@deepy I managed to fix the unit tests.

I also tried to mock the `ExecOperations` object, but did not success. But I then had another idea that finally worked. I mock the `ProjectApiHelper` instance that is used by the task. For that, I have to change the field reference, I replace its original value by the mocked one using reflection (the field is read-only in the Kotlin code).

That's not very beautiful, but what we did previously was not beautiful either. That's the same mechanism, but this time it is more visible in each test code since we need to do the trick on the task instance instead of the project one.

I'll try to write some integration tests using the configuration cache in the week-end. I'll let you know.

Have a nice day!

**Comment by bsautel** [comment]
I enabled the configuration cache in the Kotlin DSL integration test. This test can be seen as a global test since it uses all the available options and all the available task types. But it does not provide a 100% coverage of the plugin, for instance it does not download and install Node.js.

I also added the `warning-mode=fail` option to all the integration tests to ensure we don't miss any execution warnings.

I tried to enable the configuration cache on all unit tests and some tests failed. I don't know why but I need to investigate that before the release. I'll let you know!

**Comment by deepy** [comment]
With the state of things I think we should be able to merge #128 to master and then fix the `download = true` case there, I got sidetracked this weekend but during the week I should have enough time to work on things

**Comment by bsautel** [comment]
I could remove many usages of `project` from the `nodeSetup` task, but there are two usages that I don't know how to remove.

We use a repository to download a file from a Ivy repository. For that we currently use `project.dependencies` and `project.configurations`. It sounds like there is no [available service](https://docs.gradle.org/current/userguide/custom_gradle_types.html#service_injection) to do that. The code is [here](https://github.com/node-gradle/gradle-node-plugin/blob/configuration-cache/src/main/kotlin/com/github/gradle/node/task/NodeSetupTask.kt#L111).

@eskatos would you have any tip to do that from a task without using the `project`?

**Comment by bsautel** [comment]
@deepy suggested to move the file download from the task to the plugin code. I did that and it seems to be satisfying. It sounds like we are very close to close this issue.

**Comment by bsautel** [comment]
@deepy it sounds like we can close this issue, right?

**Comment by deepy** [comment]
Yeah, no reports of any issues so far either :-)

**Comment by nbrugger-tgm** [comment]
It seems that configuration cache support broke. I am using `7.1.0` and get the issues mentioned in #326
