### ISSUE TITLE
Cannot redirect stdout for NpxTask?

### ISSUE THREAD

**Issue by xpusostomos** [node-gradle/gradle-node-plugin#115]
I've done a deep dive into the code, and I can't figure out how to redirect stdout for an npx task.

If I used an Exec task, I could do this:

`        standardOutput = new java.io.FileOutputStream("$buildDir/myfile")
`

But as far as I can see there is no equivilent for NpxTask. At this point, I'd be happy to find a hack workaround.

**Comment by bsautel** [comment]
That's possible and that's explained [here](https://github.com/node-gradle/gradle-node-plugin/blob/2.2.4/docs/faq.md#how-do-i-customize-the-way-the-processes-are-launched). Something like this should solve your problem (did not test):
```groovy
execOverrides {
    it.standardOutput = new java.io.FileOutputStream("$buildDir/myfile")
  }
```
