### ISSUE TITLE
Task :nodeSetup FAILED

### ISSUE THREAD

**Issue by cdpark0530** [node-gradle/gradle-node-plugin#118]
```
* What went wrong:
Execution failed for task ':nodeSetup'.
> Could not resolve all files for configuration ':detachedConfiguration74'.
   > Could not resolve org.nodejs:node:14.13.0.
     Required by:
         project :
      > Could not resolve org.nodejs:node:14.13.0.
         > Could not get resource 'https://nodejs.org/dist/v14.13.0/ivy.xml'.
            > Could not GET 'https://nodejs.org/dist/v14.13.0/ivy.xml'.
               > peer not authenticated
```

build.gradle
```
plugins {
	...
	id 'com.moowork.node' version '1.3.1'
}

def frontendDir = "${projectDir}/frontend"

// if I comment below node block, build task goes well.
node {
	download = true
	version = "14.13.0"
	// nodeProjectDir = file(frontendDir) <- This also occurs an error!
	// Could not set unknown property 'nodeProjectDir' for extension 'node' of type com.moowork.gradle.node.NodeExtension.
}

task npmInstallFrontend(type: NpmTask) {
	workingDir = file(frontendDir)
	args = ["install"]
}

task npmBuildFrontend(type: NpmTask, dependsOn: "npmInstallFrontend") {
	workingDir = file(frontendDir)
	args = ["run", "build"]
}

task copyFrontendBackend(type: Copy, dependsOn: "npmBuildFrontend") {
	from "${frontendDir}/public"
	into "${projectDir}/build/resources/main/static"
}

build.dependsOn copyFrontendBackend
```

The issue occurs when you setup node block like described above. Whether you specify version or not, it still occurs the error and if you don't specify the version, it tries to use version 10.15.3 which is very old.
An additional issue is that when I try to use nodeProjectDir property as described [here](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/usage.md), gradle says `Could not set unknown property 'nodeProjectDir' for extension 'node' of type com.moowork.gradle.node.NodeExtension`.

**Comment by bsautel** [comment]
You are not using the right plugin. This plugin is a fork of the one you are currently using and that is no longer maintained. Update to the latest version of this plugin and this should work.

**Comment by cdpark0530** [comment]
> You are not using the right plugin. This plugin is a fork of the one you are currently using and that is no longer maintained. Update to the latest version of this plugin and this should work.
@bsautel Right, I knew it just few minutes after I wrote this. Thank you for your reply.

**Comment by johnterrill** [comment]
I encountered the same error using the [traditional Gradle way](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/installation.md#installation) of installing plugins. Changing the install to the `plugins`-closure fixed the issue.

Error:
```
* What went wrong:
 Execution failed for task ':NodeProject:nodeSetup'.
 > Could not resolve all files for configuration ':NodeProject:detachedConfiguration1'.
    > Could not resolve org.nodejs:node:12.18.3.
      Required by:
          project :NodeProject
       > Could not resolve org.nodejs:node:12.18.3.
          > Could not get resource 'https://jcenter.bintray.com/org/nodejs/node/12.18.3/node-12.18.3.pom'.
             > Could not GET 'https://repo.jfrog.org/artifactory/libs-release-bintray/org/nodejs/node/12.18.3/node-12.18.3.pom?referrer'.
                > Read timed out
```

Traditional Gradle install (causes error)
```
buildscript {
  repositories {
    maven {
      gradlePluginPortal()
    } 
  }

  dependencies {
    classpath "com.github.node-gradle:gradle-node-plugin:2.2.4"
  }
}

apply plugin: 'com.github.node-gradle.node'
```

`plugins`-closure install
```
plugins {
  id "com.github.node-gradle.node" version "2.2.4"
}
```
Possibly related, I'm using the Android Gradle tools: `com.android.tools.build:gradle:4.0.0`

**Comment by deepy** [comment]
Internally where I work we use the traditional style without problems, which makes me wonder if your error isn't because of the timeout from jfrog

**Comment by johnterrill** [comment]
@deepy jfrog timing out probably makes more sense; we started seeing this issue this morning out of the blue.
