### ISSUE TITLE
yarn tasks don't use gradle cache

### ISSUE THREAD

**Issue by christian-draeger** [node-gradle/gradle-node-plugin#121]
I am wondering if there is a way to use the gradle cache if the input sources to the task haven't changed. currently it will execute the yarn task even if no files has changed.

is there a way / workaround / configuration to have it cached?

here an example:
![image](https://i.ibb.co/Rc8qGkp/node-plugin-not-cached.gif)

**Comment by deepy** [comment]
Looking at your configuration and the tasks that you're running, there's no inputs or outputs added.
The autogenerated `yarn/npm_foo` tasks don't have any output defined (as there's no real way of knowing what they'll produce or even if they will)

So my recommendation is that you register `YarnTask` tasks with the camelCase names for each `yarnTestCi`, `yarnBuild`, etc
And adding your inputs and outputs to the relevant tasks.
There's a very good description of this and how it works at https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks and at https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:runtime_api_for_adhoc there's some examples
