### ISSUE TITLE
Task yarnSetup does not respect proxy settings

### ISSUE THREAD

**Issue by boerngen-schmidt** [node-gradle/gradle-node-plugin#122]
Hey,

in 3.0.0-rc3 when I run gradle yarnSetup so that the latest version of yarn is downloaded it does not seem to respect the gradle proxy settings with `useGradleProxySettings = true`

when I set the proxy in ~/.npmrc with [px](https://github.com/genotrance/px) as my local proxy
```
proxy=http://localhost:3128/
https-proxy=http://localhost:3128/
;strict-ssl=false
;registry=http://registry.npmjs.org/
```
it works just fine.

build.gradle looks like
```
plugins {
    id "com.github.node-gradle.node" version "3.0.0-rc3"
}

group 'foo.bar'
version '0.1'

node {
    download = true
    version = "12.19.0"
    useGradleProxySettings = true
}
```

`gradle properties` yields that the proxy is correctly set
```
systemProp.http.proxyHost: localhost
systemProp.http.proxyPort: 3128
systemProp.https.proxyHost: localhost
systemProp.https.proxyPort: 3128
```

**Comment by deepy** [comment]
@boerngen-schmidt do you have any proxy configuration in environment variables?

If any of these are present the plugin does not set proxy settings (as it'd potentially partially override your own config) https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/github/gradle/node/npm/proxy/NpmProxy.kt#L14 (and line 20)

**Comment by boerngen-schmidt** [comment]
Steps I take to debug:
`rm -rf .grade/*; npm cache clean --force; gradle yarnSetup`
My proxysettings are globally set in USERHOME/.gradle/gradle.properties

Without .npmrc settings:
 - Windows Powershell there is no http(s)_proxy environment vars set. --> not working
 - Windows Powershell with environment --> working
 - Gradle Task from IntelliJ --> not working
 - msys2 without environment --> not working
 - msys2 with environmet --> working

**Comment by boerngen-schmidt** [comment]
@deepy I tried to read and understand the source code, but the kotlin syntax still confuses me a little. But as far as I could backtrack it, the plugin only sets a proxy if 

1. useGradelProxySettings is true 
1. there is no system Proxy settings

I would suggest to do it differently, because if someone does set any Proxy settings they probably have a proxy. So I would check the following order

1. Check enableProxySetting. (if disabled skip any proxy configuration by plugin for node, npm and yarn)
1. Check and apply "OS" Proxy settings (most generic)
1. Check and apply proxysettings from Gradle, overwriting System

According to https://docs.npmjs.com/cli/v6/using-npm/config npm will honor the environment variables like HTTP_PROXY etc. if they are set. I do not know if gradle will make them available when executing a command or if the environment is blank. My guess is they are blank and that is why you explicitly test for them.

Also I would recommend to use commandline flags when running any command, since they have the highgest priority over environment and npmrc settings.

**Comment by deepy** [comment]
Maybe we should switch `useGradleProxySettings` from a Boolean to an enum, having something like: off, automatic, and forced as options.

The reason we switched to environment variables is for extended support, e.g. `npm` will take `--proxy` but `npx` won't and `NodeTask`s that you run might not accept `--proxy` but they'll either support or happily ignore `HTTP_PROXY` being set.

Now this has some drawbacks, and my favourite is that it doesn't show up in `npm config -ls`.

But just to clarify, when you mention "OS" proxy settings, do you mean the Java settings that we currently read? or the [java.net.useSystemProxies](https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html) (which I'm pretty sure also works on macOS but is less reliable on Linux)

**Comment by boerngen-schmidt** [comment]
With OS proxy settings I mean the environment variables `HTTP_PROXY` and `HTTPS_PROXY` like you pointed to in you link to NpmProxy.kt. They are the broadest way of setting a system-wide proxy for Linux, Mac and Windows and are respected by most applications.

For the JVM one could, as you linked correctly, also set proxy configuration, but these are JVM specific settings.

As for the usage of environment variables I fully understand your point. I only looked at npm and nothing else.

I think I also found the problem why the gradle proxysettings are not respected. On https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/github/gradle/node/npm/proxy/NpmProxy.kt#L47 the property ´http.proxyHost´ is read, which would correspond with the JVM property you linked to earlier. But Gradle uses ´systemProp.http.proxyHost´ for its configuration according to https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy

**Comment by deepy** [comment]
In Gradle's case it lets you set system properties through `systemProp`, so `systemProp.https.proxyHost` would be equivalent to `-Dhttps.proxyHost` and would be retrieved by `System.getProperty("https.proxyHost")`.

I really should've added some debug logging so that we could just have used `--debug` and gotten an idea on where it was failing, but I did test it personally and even got the integration tests reporting success.

But just to confirm, do you have any of the following environment variables set? `"HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY", "PROXY"`
Or `"NPM_CONFIG_PROXY", "NPM_CONFIG_HTTPS-PROXY", "NPM_CONFIG_NOPROXY"`?

**Comment by boerngen-schmidt** [comment]
I do **NOT** have any of these environment variables set.
I have set the proxy vars in ~/.gradle/gradle.properties just for gradle.

If you could instruct me on how I can use the plugin if I compile it myself locally then I could do some tests on my own and see what is not working correctly.

**Comment by deepy** [comment]
If you add `--include-build <path to gradle-node-plugin git repository>` or add it in `settings.gradle` as an `includedBuild` it should use the plugin from that place, that's from what I recall the easiest way to test things.

Well, the easiest way would be to write an integration test in `gradle-node-plugin` and run it directly there, `./gradlew build test --tests "Npm_integTest"`

**Comment by deepy** [comment]
Next RC is getting a `ProxySettings.FORCED` which should solve this
