### ISSUE TITLE
Could not find node version

### ISSUE THREAD

**Issue by junhoi-pk** [node-gradle/gradle-node-plugin#124]
The following error occurs a few days ago.

```
> Task :xxx:nodeSetup FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xxx:nodeSetup'.
> Could not resolve all files for configuration ':ranchat-admin:detachedConfiguration1'.
   > Could not find node-14.4.0-linux-x86.tar.gz (org.nodejs:node:14.4.0).
     Searched in the following locations:
         https://nodejs.org/dist/v14.4.0/node-v14.4.0-linux-x86.tar.gz

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

Below is my gradle config
```
node {
    version = '14.4.0'
    npmVersion = '6.14.4'
    distBaseUrl = 'https://nodejs.org/dist'
    download = true
    workDir = file("${projectDir}/src/main/nodejs")
    npmWorkDir = file("${projectDir}/src/main/js")
    nodeModulesDir = file("${project.projectDir}/src/main/js")
}
```

I tried changing the node version, but the problem is the same.

**Comment by deepy** [comment]
You'll need to downgrade far, I think nodejs 8 was the last version with 32-bit support. see https://github.com/nodejs/build/issues/885 for full information.

You can probably use the unofficial builds with `distBaseUrl` but there's no support for 32-bit so I recommend upgrading your systems,

**Comment by junhoi-pk** [comment]
@deepy 
But I have never changed the version,
Just a day ago, it worked very well.

However, I upgraded the Java version from 11.0.3 to 11.0.9. Is this related?

Thx

**Comment by junhoi-pk** [comment]
@deepy And my server is x86_64

**Comment by deepy** [comment]
@junhoi-pk this plugin will get the system architecture from the JVM, you might have accidentally installed a 32-bit JVM and as a result the plugin is seeing a 32-bit system.

You can verify this with `java -version`

```
...
OpenJDK 64-Bit Server VM AdoptOpenJDK
```

**Comment by junhoi-pk** [comment]
Thank you very much.
Thanks for finding the solution

The jdk version was installed as 32bit.
