### ISSUE TITLE
What's the relation ship of this plugin with another plugin(com.moowork.gradle)?

### ISSUE THREAD

**Issue by hql1991** [node-gradle/gradle-node-plugin#126]
So there's [another repo ](https://github.com/srs/gradle-node-plugin) hosted on GitHub too, and it's also published in the [official gradle plugin repo](https://plugins.gradle.org/plugin/com.moowork.node). And my organization is currently using both plugins in a mix, causing a lot of confusion when maintaining. To make matters worse, the 2.2.3 release of this repo, which my organization is using, will build to have implementation-class "com.moowork.gradle.node.NodePlugin".

Could someone help me understand the history?

**Comment by cdietrich** [comment]
srs is unmaintained and this is the fork/place that makes the stuff living.
class renaming is happening with the new release that is currently in work.

**Comment by hql1991** [comment]
Thanks @cdietrich for quick reply. That explains all my questions, thank you so much!
