### ISSUE TITLE
npmInstall and npm_install are handled different

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#13]
If you use `npm_install` you get a different task than the default pre-configured one at `npmInstall`.

The `npm_` rule should probably check if the `npmInstall` task exists and return that, otherwise create a new `NpmInstallTask`.

**Comment by ddebree** [comment]
I had a similar problem. 
In the docs/faq file there is mention that the way to do incremental builds is to add the following `dependsOn yarn_install`. 
Based on this, I added `dependsOn npm_install` to my configuration. 
The problem with this is that npm_install does not have inputs/outputs defined, and so gradle always runs it. When I changed to `dependsOn npmInstall` things work correctly, and the install step is skipped if I don't change the package.json file.

**Comment by deepy** [comment]
That'll get resolved with this issue :-)
Although it makes me wonder if we even should support the automagic task creation as it is today.
I can see the value in doing it automagically for things like `npm_run_foo` but in its current state it makes `npm_ci` impossible

**Comment by stefanneuhaus** [comment]
I did not yet get why running `npm_ci` is not possible in its current state.

Besides that IMHO there is no big problem in having `npmInstall` behave differently than `npm_install`. At least this is no breaking change. To me this maybe surprising behavior is the price for the trade-off we made to only have a small change to support ci. The cleaner (but bigger) change would have been to implement option 1 as proposed in #7.

**Comment by deepy** [comment]
I like option 1 which is likely where we are going with next major, but the reason that `npm_ci` is not possible is because of https://github.com/node-gradle/gradle-node-plugin/blob/9484b92fc7a374dfbd7c638912bbb7aea2a62796/src/main/groovy/com/moowork/gradle/node/NodePlugin.groovy#L89
All autogenerated `npm_` tasks depends on `npmInstall` so if you run `npm_install` you'll first run `npmInstall` and then `npm_install`

The issue with `npm_install` is that it lacks inputs/outputs and caches badly (unless you manually specify them) and that it depends on `npmInstall`

**Comment by deepy** [comment]
Since I can't get a single task with two names I'm going with this solution:
`npm_install` will be legit but will provide a warning about how `npmInstall` is probably also going to run and recommending that you configure `npmInstall` rather than using `npm_install`.
`npm_install` will be created as a `NpmInstallTask` rather than `NpmTask`
