### ISSUE TITLE
Calling NPM task takes too long time

### ISSUE THREAD

**Issue by wonsuc** [node-gradle/gradle-node-plugin#133]
I have a **Spring Boot project** and trying to implement **React.js with Create React App** source code.  (IDE is IntelliJ 2020.3, JDK Amazon Corretto 15.0.1)

I'm trying to run this single task with this plugin.  (with option `download = false`)

```
task appNpmBuild(type: NpmTask) {
    description = "Builds production version of the webapp"
    workingDir = file("${project.projectDir}/src/main/webapp/react")
    args = ["run", "build:production"]
}
```

It takes 3 min 25 sec for me.  Here are the full logs.  

```
PM 5:09:21: Executing task 'appNpmBuild'...

Starting Gradle Daemon...
Gradle Daemon started in 3 s 254 ms
Parallel execution with configuration on demand is an incubating feature.
> Task :nodeSetup SKIPPED
> Task :npmSetup SKIPPED

> Task :appNpmBuild

> ips@0.1.0 build:production C:\Dev\source\code\IdeaProjects\IPS\src\main\webapp\react
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  41.2 KB  build\static\js\2.46bbb8b1.chunk.js
  1.39 KB  build\static\js\3.855444d8.chunk.js
  1.16 KB  build\static\js\runtime-main.6274922d.js
  401 B    build\static\js\main.f9452047.chunk.js
  273 B    build\static\css\main.9139d0d2.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment


BUILD SUCCESSFUL in 3m 25s
1 actionable task: 1 executed
PM 5:12:47: Task execution finished 'appNpmBuild'.

```

However if I just use a terminal, it takes only 29 seconds.  

```
"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run build:production --scripts-prepend-node-path=auto

> ips@0.1.0 build:production C:\Dev\source\code\IdeaProjects\IPS\src\main\webapp\react
> react-scripts build | gnomon

  26.0109s   Creating an optimized production build...
   0.0012s   Compiled successfully.
   0.0003s  
   0.0003s   File sizes after gzip:
   0.2572s  
   0.0006s     41.2 KB  build\static\js\2.46bbb8b1.chunk.js
   0.0004s     1.39 KB  build\static\js\3.855444d8.chunk.js
   0.0006s     1.16 KB  build\static\js\runtime-main.6274922d.js
   0.0003s     401 B    build\static\js\main.f9452047.chunk.js
   0.0003s     273 B    build\static\css\main.9139d0d2.chunk.css
   0.0003s  
   0.0003s   The project was built assuming it is hosted at ./.
   0.0004s   You can control this with the homepage field in your package.json.
   0.0002s  
   0.0010s   The build folder is ready to be deployed.
   0.0002s  
   0.0003s   Find out more about deployment here:
   0.0004s  
   0.0004s     https://cra.link/deployment
   2.9710s  
   0.0006s  
            
     Total   29.2575s

Process finished with exit code 0
```

I tried with Gradle version with 4.x, 5.x, 6x, and all same result.  
I tried stable 2.2.4 of this plugin and 3.0.0-rc5 and same result.  

Am I missing something?

**Comment by deepy** [comment]
from 30s to 3m sounds pretty big but since this is an entire build there might be something else, you can run with `--profile` to get a local report of what takes time (or `--scan` for an online report that's more sophisticated and can be shared).
It'd be interesting to see what is taking time, there shouldn't be a difference this large, most importantly the `appNpmBuild` should be about as fast as running the `npm` command locally

**Comment by wonsuc** [comment]
@deepy Ok, I tried `--scan`, and here is the link.

https://scans.gradle.com/s/5hxojehgq4doo

**Comment by deepy** [comment]
Hmm, that's indeed the task taking 3m19s to execute and since there's no outputs registered on the task it's not input/output checking being slow on windows either.

`NpmTask` is really just a wrapper around running `npm`, there's not really any code running in the exec stage so I'd expect `npm` run from the command-line and run from `NpmTask` to be within 1-2 seconds of each other.

However 3m is also around the build-time I'd *expect* from a npm build, but just to make certain, both of these builds are run from a clean working directory? (like running `git clean -fqdx` to remove *all* changes before measuring)

And out of curiosity, if running with gnomon in the `NpmTask`, does it show 3m for `Creating an optimized production build...`?

**Comment by wonsuc** [comment]
@deepy I found this also happens on a terminal when I run with `gnomon` with this command.  

```
C:\Dev\source\code\IdeaProjects\IPS\src\main\webapp\react>npm run build:production | gnomon
   4.7584s  
   0.0010s   > ips@0.1.0 build:production C:\Dev\source\code\IdeaProjects\IPS\src\main\webapp\react
   0.0016s   > react-scripts build
  26.1325s  
  32.3843s   Creating an optimized production build...
   0.0062s   Compiled successfully.
   0.0045s  
   0.0011s   File sizes after gzip:
   0.1661s  
   0.0066s     41.2 KB  build\static\js\2.46bbb8b1.chunk.js
   0.0096s     1.39 KB  build\static\js\3.855444d8.chunk.js
   0.0080s     1.16 KB  build\static\js\runtime-main.6274922d.js
   0.0012s     401 B    build\static\js\main.f9452047.chunk.js
   0.0033s     273 B    build\static\css\main.9139d0d2.chunk.css
   0.0006s  
   0.0007s   The project was built assuming it is hosted at ./.
   0.0004s   You can control this with the homepage field in your package.json.
   0.0005s  
   0.0004s   The build folder is ready to be deployed.
   0.0006s  
   0.0006s   Find out more about deployment here:
   0.0004s  
   0.0007s     https://cra.link/deployment
 127.6015s  
   0.0010s  
            
     Total   191.1990s
```

I have no idea what is happening during `127.6015s`...

**Comment by deepy** [comment]
I wonder if it might be related to the output being buffered, `gnomon --real-time=false` might fix that.

But it's strange that it should affect it at all, if time permits I'll try setting up a react-scripts build this weekend and see if I can reproduce

**Comment by wonsuc** [comment]
I tried `gnomon --real-time=false` and it didn't fix the problem.  

I'm actually working at Samsung(as a partner worker), and the environment is proxy behind, and many security programs are installed. Can it matter?

**Comment by deepy** [comment]
Proxy shouldn't be an issue unless `npm install` is being run, and in that case there should be (and usually is) an internal mirror/repository being used (e.g. nexus/artifactory/etc)

Security programs however are a different beast, when Cinnober got acquired by Nasdaq we switched security software and as a result some Windows users are seeing build times of >=10 minutes compared to the <=3 minutes on other operating systems.

And my terminal which prints the current git branch of the project I'm in also takes about 2-3 times longer to run, and sometimes takes 10-15 seconds.

However, I don't think there should be a big difference on whether you launch npm yourself or if it's being launched by Gradle, so it should really be consistently slow or just sometimes slow (e.g. when a scan hits).

One way to mitigate this would be to use the build-cache for the `appNpmBuild` task, and if you can use a remote build cache populated by the CI environment (e.g. gradle enterprise or the free [build-cache-node](https://hub.docker.com/r/gradle/build-cache-node/)).
That way you'd only have to re-build it when files have changed and when they haven't Gradle would just fetch it from the cache instead.
In my team we use a different approach, many prefer to use npm directly while working on it and use hot-reloading with a proxy, so the npm project can be worked on without rebuilding the java application.

**Comment by wonsuc** [comment]
Thank you for the detailed description.  
I was going to close this issue and somehow I found this StackOverflow question.  
https://stackoverflow.com/q/61406695/4729203
The OP having the exact same issue but it seems he couldn't find the reason as well...

**Comment by wonsuc** [comment]
I think it's proxy related issue.  
Can you try to reproduce with proxy behind environment?  
Thank you...

**Comment by deepy** [comment]
If you're able to install software locally I can recommend the following for troubleshooting, download nexus or artifactory, run it locally (configure proxy in it), and then set the npm `registry` in `.npmrc` to the nexus/artifactory mirror of npm, first build should probably be slower but after a build or two it should have eliminated any latency issues possible.

**Comment by wonsuc** [comment]
@deepy Thank you for the good advice.

**Comment by wonsuc** [comment]
I found an interesting result. 
I disconnected the internet connection during the build, and it doesn't make a delay issue.

**Comment by wonsuc** [comment]
Okay, I figured it out.
Migrating to Yarn fixed the issue, and now it works perfectly.
Thank you for the support :)
