### ISSUE TITLE
Add FAQ/usage entry about dependencyResolutionManagement together with gradle-node-plugin

### ISSUE THREAD

**Issue by dawi** [node-gradle/gradle-node-plugin#134]
Gradle 6.8 introduces the "Central declaration of repositories".

https://docs.gradle.org/6.8/release-notes.html#central-declaration-of-repositories

If I use this new feature in our project together with the `gradle-node-plugin`, some Java libraries cannot be resolved.

To track down the issue, I have added the flag `FAIL_ON_PROJECT_REPOS` to the configuration:

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven("https://some-internal-nexus/repository/repo/")
    }
}
```

This shows the cause of the issue:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wicket-components:nodeSetup'.
> Build was configured to prefer settings repositories over project repositories but repository 'ivy' was added by unknown code
```

It seems that an Ivy repository is added to the project which seems to be the cause of the issue.

**Comment by deepy** [comment]
If you set `distBaseUrl` to `null` it should work, but you'll have to add the `IvyRepository` yourself if you want to be able to use `download = true`

**Comment by deepy** [comment]
I suspect what you really want is `RepositoriesMode.PREFER_SETTINGS`

**Comment by dawi** [comment]
It seems so at first glance, but `RepositoriesMode.PREFER_SETTINGS` will cause the `IvyRepository` to be ignored.

```java
/**
 * If this mode is set, any repository declared directly in a project,
 * either directly or via a plugin, will be ignored.
 */
PREFER_SETTINGS,
```

I think I will open a `gradle` ticket also. In the current state, I cannot use the centralized repository declartion.
Because I still have to declare the repository at the project level, because otherwise the `IvyRepository` is ignored.

It would be great if `gradle` had an option that would behave exactly as if the repository was defined at project level.

**Comment by deepy** [comment]
Well you could create the `IvyRepository` yourself, though you might not want to add it to all projects.
Alternately maybe you can make the node build an `includedBuild` and let that have a different configuration?

**Comment by dawi** [comment]
Yes, but all those things are just workarounds in my opinion.

For now I will continue to declare the repository via `allprojects` (so also in one place).
I just liked the idea, to move repository configuration from build to settings. Sadly it didn't work out.

https://github.com/gradle/gradle/issues/15754

**Comment by bsautel** [comment]
I added a dependency resolution management policy to an integration test.

It obviously fails with `FAIL_ON_PROJECT_REPOS`, that's logical. But I confirm it also fails with `PREFER_SETTINGS`.

For now, the test uses `PREFER_PROJECT` which seems to correspond to the former behavior. I'll adjust if anything changes thanks to gradle/gradle#15754. The issue has been added to the 6.8.1 milestone, so we can expect some news soon.

**Comment by deepy** [comment]
The solution to your problem @dawi is in this comment: https://github.com/gradle/gradle/issues/15754#issuecomment-763614651
Adding an IvyRepository with content specification manually.

I'm repurposing this issue to document how to do this.

**Comment by deepy** [comment]
There's a brief integration test that proves that this works, I'll extract that into documentation tomorrow-ish

**Comment by bsautel** [comment]
I added [a section](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/faq.md#is-this-plugin-compatible-with-centralized-repositories-declaration) in the FAQ explaining how to use the plugin when using the centralized repositories declaration.

I also added a test to ensure that the plugin works by default when using the centralized repositories declaration and `download = false`.

Please let me know if you have any feedback. Otherwise I think we can close the issue.

**Comment by dawi** [comment]
@bsautel I've already configured it in the same way you documented and it works well.

Maybe a few suggestions regarding the documentation:

* It seems that the code is Kotlin DSL, therefore the headlines should be `build.gradle.kts` and `settings.gradle.kts`.
* I am note sure, but I think `ivy("v[revision]/ivy.xml")` does not need to be configured.
* Instead of `setUrl("https://nodejs.org/dist/")` it could be `url = "https://nodejs.org/dist/"` to be consistent with `name = "Node.js"`

**Comment by bsautel** [comment]
Thanks @dawi for your feedback! I fixed that. And I confirm this uses the Groovy DSL.

**Comment by deepy** [comment]
The reason for `setUrl()` was for kotlin compatibility, while this works in groovy in kotlin it gives a Type mismatch as `getUrl()` returns an `URI`

**Comment by deepy** [comment]
And before anyone thinks "Aha! That makes sense, but we should switch to the setter for name as well!" if you do that, IntelliJ will helpfully tell you that you should use the property access syntax instead 😈

**Comment by deepy** [comment]
I've removed the `ivy()` call from the plugin itself as well, pushed it to run the tests, and reverted the change in the documentation to make it kotlin copy-paste friendly

**Comment by bsautel** [comment]
Ok, perfect! Thanks!

**Comment by dawi** [comment]
Just in case someone want's to set `distBaseUrl` to `null` via Kotlin DSL, here is how:

```
configure<NodeExtension> {
    distBaseUrl.set(null as String?) // to prevent IvyRepository to be created via NodePlugin
}
```
