### ISSUE TITLE
how to properly subclass NodeTask with 3.0.0.x

### ISSUE THREAD

**Issue by cdietrich** [node-gradle/gradle-node-plugin#137]
hi, how do i properly create a subclass for NodeTask

```
> startup failed:
  build file '/Users/cdietrich/xtext-master/git/xtext-web/org.eclipse.xtext.web/build.gradle': 50: Can't have an abstract method in a non-abstract class. The class 'OptimizationTask' must be declared abstract or the method 'org.gradle.api.provider.ProviderFactory getProviders()' must be implemented.
   @ line 50, column 1.
     class OptimizationTask extends com.github.gradle.node.task.NodeTask {
     ^
```

```
class OptimizationTask extends com.github.gradle.node.task.NodeTask {
	OptimizationTask() {
		dependsOn(project.npmInstall)
		inputs.dir 'src/main/js'
		script.set(project.file('node_modules/requirejs/bin/r.js'))
		def logLevelWarn = 2 // WARN
		args.add('-o')
		args.add('logLevel=' + logLevelWarn)
	}
	def setBuildProfile(File buildProfile) {
		def l = new ArrayList<String>(args.get())
		l.add(1, buildProfile.path)
		args.set(l)
	}
	def setCssInput(File cssInput) {
		inputs.file cssInput
		args.add('cssIn=' + cssInput)
	}
	def setOutput(File output) {
		outputs.file output
		args.add('out=' + output.path)
	}
	def setOptimize(String optimize) {
		args.add('optimize=' + optimize)
		if (optimize != 'none')
			args.add('preserveLicenseComments=false')
	}
}
```

**Comment by cdietrich** [comment]
marking the class as abstract seems to work
abstract class OptimizationTask extends com.github.gradle.node.task.NodeTask {
but i am not sure if this is correct

**Comment by bsautel** [comment]
The `NodeTask` class (and all the other ones) are abstract.

They use the [service injection](https://docs.gradle.org/current/userguide/custom_gradle_types.html#service_injection) mechanism. We need those services such as `ObjectsFactory` to implement the task without depending on the `Project` class which is necessary to support the configuration cache mechanism.

To ease the injection, you can define some abstract classes with abstract getter methods annotated with `@Inject` that are automatically generated by Gradle when instantiating the class. Making your class abstract should solve this issue.

**Comment by cdietrich** [comment]
thx
