### ISSUE TITLE
NpxTask with 'es-check' is not working.

### ISSUE THREAD

**Issue by donggyu04** [node-gradle/gradle-node-plugin#139]
Hi, I want to just run [es-check](https://www.npmjs.com/package/es-check) in gradle build script with NpxTask. so I made a very simple gradle task for testing.
I thought these two tasks would be run like below. but both aren't. Please correct me if i'm wrong.

### 1. Simple task
```
task testNpx(type: NpxTask) {
    command = 'es-check'
}
```
```
task testNpx(type: NpxTask) {
    command = 'es-check'
    args = ['es5', '{bundled-javascript-file-absolute-path}, '--verbose']
}
```
### 2. Expected npx command
```
npx es-check 
```
```
npx es-check es5 {bundled-javascript-file-absolute-path} --verbose
```

### 3. Result

1. Task
```
// Two tasks have the same result below.

Execution failed for task ':testNpx'.
> Process 'command '/Users/user/dev/.gradle/nodejs/node-v14.15.4-darwin-x64/bin/npx'' finished with non-zero exit value 1
```
2. Run npx with iTerm

```
npx es-check 

No ecmaScript version passed in or found in .escheckrc. Please set your ecmaScript version in the CLI or in .escheckrc
```

```
npx es-check es5 {bundled-javascript-file-absolute-path} --verbose

ES-Check: Going to check files using version 5
ES-Check: checking {bundled-javascript-file-absolute-path}
ES-Check: there were no ES version matching errors!  🎉
```

### 4. My environment 

- macOS 10.15.7
-  gradle-node-plugin: 2.2.4
- node version : 14.15.4

**Comment by bsautel** [comment]
It sounds like what you are doing is right.
Could you show us the Gradle output when adding `--info` to the Gradle command? It should print the command which is executed, this will probably help us to understand what's happening.
The interesting log line should start with `Starting process 'command 'npx''`.

**Comment by donggyu04** [comment]
@bsautel 

It's not a gradle-node-plugin problem.
My mistake made this. That works fine.

Thanks for your support :)
