### ISSUE TITLE
gradle-versions-plugin not working OK with gradle-node-plugin

### ISSUE THREAD

**Issue by boris-petrov** [node-gradle/gradle-node-plugin#142]
The issue title is not very good. See [this answer](https://github.com/ben-manes/gradle-versions-plugin/issues/343#issuecomment-774335525) and the couple of messages before it for context. Could this be done for 3.0 so that I can check for dependency updates again and not hammer Node.js' site with millions of useless requests? :smile:

**Comment by bsautel** [comment]
We recently added (just after the 3.0.0-rc7 release) content filtering to the Node.js repository declaration. See [here](https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/github/gradle/node/NodePlugin.kt#L88) in the source code. As far as I understand, I should solve this issue, shouldn't it?

**Comment by ben-manes** [comment]
I would think so, but @boris-petrov's log showed Gradle trying to resolve jars against that repository. Maybe he's using an older release?

Do you use a specific configuration for js dependencies? If so, you could use `onlyForConfigurations​(string)` to limit the repository's usage.

**Comment by bsautel** [comment]
The content filtering is not present in the latest (3.0.0-rc7) release. It maybe explains why @boris-petrov still encounters this issue. @deepy what do you think about publishing a new rc that embeds this change?

We use a [detached configuration](https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/github/gradle/node/NodePlugin.kt#L119). As far as I understand, it is an anonymous configuration detached from the configurations container, so we probably can't use `onlyForConfigurations()`.

**Comment by deepy** [comment]
I'll brew some coffee and start working on getting 3.0 released, with no bug reports regarding the configuration cache we should be good for releasing

**Comment by deepy** [comment]
With 3.0.0 released this should no longer be an issue, if you need this for the `2.x` version, use `distBaseUrl = null` and manually add the `IvyRepository`

**Comment by boris-petrov** [comment]
Confirmed! Version 3.0.0 final fixes the issue! Thanks everyone for the great support!
