### ISSUE TITLE
Confirm npmInstall hits ~/.npm cache?

### ISSUE THREAD

**Issue by SkylerLutz** [node-gradle/gradle-node-plugin#143]
Hi,

How can I confirm that npmInstall task hits the ~/.npm cache? My clean builds are slow and I don't think it's using the NPM cache. 

Thanks

**Comment by bsautel** [comment]
The `npmInstall` task simply runs `npm install` or `npm ci` according your configuration. It does not change the behavior of these commands regarding the cache. As far as I know npm caches by default and that should not change using the Gradle plugin.
See my answer to #141, it should help you to know why your build is slow.

**Comment by bsautel** [comment]
@SkylerLutz can we close this issue?
