### ISSUE TITLE
Unable to update to v3.0.1

### ISSUE THREAD

**Issue by abendt** [node-gradle/gradle-node-plugin#146]
Hi folks,

we are currently using this plugin (v2) in one project. When trying the new version the build fails:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':module'.
> Exception while analyzing expression at (15,7) in /private/var/folders/_4/3px8nr_x243399h66bkn08j00000gn/T/gradle-kotlin-dsl-12987683001214076514/build.gradle.kts
```

i have created a stripped down sample project to reproduce the issue:
https://github.com/abendt/gradle-node-plugin-bug

```
$ cd module
$ ../gradlew build
```

**Comment by bsautel** [comment]
The error message is very poor and I did not try to build locally your project, but at line 15 you use `YarnTask`.

Its package changed in version 3.0.0 (see the changelog).

You are still using the old package:
```kotlin
import com.moowork.gradle.node.yarn.YarnTask
```
You should import it from:
```kotlin
import com.github.gradle.node.yarn.task
```

I'm not sure this will completely solve your problem, but you need to change that.

**Comment by abendt** [comment]
ok, thanks

yes, there are some more issues but they are all mentioned in changelog

should have checked it better.

thanks again!

**Comment by bsautel** [comment]
Ok, I close the issue. Comment it again if you get other issues.
