### ISSUE TITLE
Specify node + npm paths when download=false

### ISSUE THREAD

**Issue by SkylerLutz** [node-gradle/gradle-node-plugin#147]
Hi,

Question about this part of [usage](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/usage.md):

```
// Whether to download and install a specific Node.js version or not
// If false, it will use the globally installed Node.js
// If true, it will download node using above parameters
// Note that npm is bundled with Node.js
download = false
```

I was wondering if it is possible to specify a local version of node & npm with download=false? e.g.

```
nodeExecutable = '/path/to/local/node/installation/'
npmExecutable  = '/path/to/local/npm/installation/'
```

Thanks in advance

**Comment by deepy** [comment]
It'll use the first one found on `PATH`, if you really need to override this on a task level you could set the environment variable in `execOverrides`.

Generally if you want to make certain a specific version is used, the easiest way is by using `download = true`
