### ISSUE TITLE
Yarn tasks doesn't work on environment without node installed

### ISSUE THREAD

**Issue by tmarton** [node-gradle/gradle-node-plugin#149]
Hello,

I'm experiencing troubles running my yarn tasks on Gitlab CICD using official gradle image. 
This gradle image doesn't contain node binaries, so when yarn binary wants to execute `/usr/bin/env: node` it throws an error.
In my opinion it should use node downloaded by gradle-node-plugin. Is it a bug or am I missing something ?

Here is my configuration
`apply plugin: "com.github.node-gradle.node"
node {
        // versions are defined in gradle.properties
        // the downloaded version is cached across builds
        download = true

        version = project.nodeVersion
        workDir = file("${rootDir}/.gradle/node")
        nodeModulesDir = rootDir

        yarnVersion = project.yarnVersion
        yarnWorkDir = file("${rootDir}/.gradle/yarn")
    }`

And here is my stacktrace:
`
Welcome to Gradle 6.6.1!
Here are the highlights of this release:
 - Experimental build configuration caching
 - Built-in conventions for handling credentials
 - Java compilation supports --release flag
For more details see https://docs.gradle.org/6.6.1/release-notes.html
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :assembly:nodeSetup
> Task :assembly:yarnSetup
/builds/engineering/src/one/mmm/one-metadata-frontend/.gradle/yarn/yarn-v1.22.5/bin/yarn -> /builds/engineering/src/one/mmm/one-metadata-frontend/.gradle/yarn/yarn-v1.22.5/lib/node_modules/yarn/bin/yarn.js
/builds/engineering/src/one/mmm/one-metadata-frontend/.gradle/yarn/yarn-v1.22.5/bin/yarnpkg -> /builds/engineering/src/one/mmm/one-metadata-frontend/.gradle/yarn/yarn-v1.22.5/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.5
added 1 package in 0.412s
> Task :assembly:yarn
/usr/bin/env: ‘node’: No such file or directory
 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':assembly:yarn'.
> Process 'command '/builds/engineering/src/one/mmm/one-metadata-frontend/.gradle/yarn/yarn-v1.22.5/bin/yarn'' finished with non-zero exit value 127
* Try:
> Task :mmm-fe-frontend:nodeSetup
4 actionable tasks: 4 executed
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 57s`

**Comment by deepy** [comment]
It sounds to me like you're on musl, is your CI running on alpine linux?

You'll have to switch to a non-musl image, get one with node installed already, or point to the unofficial builds https://github.com/node-gradle/gradle-node-plugin/issues/51
