### ISSUE TITLE
Suggestions for plugin improvements

### ISSUE THREAD

**Issue by imanushin** [node-gradle/gradle-node-plugin#15]
Because of issue https://github.com/srs/gradle-node-plugin/issues/315 I suggest to:

* ~Rename plugin (to avoid collision on the [plugin storage](https://plugins.gradle.org/)).~
* ~Redirect source code to this project of the newly published plugin~
* Configure publication by using one of the popular build systems
* Drop compatibility with the old code:
  * Use Java 8+(probably java 11+ to reduce platform variability)
  * ~Use Gradle 5.4.1 (the latest one)~

**Comment by deepy** [comment]
Is there currently a collision or need to redirect?
https://plugins.gradle.org/plugin/com.github.node-gradle.node
https://plugins.gradle.org/plugin/com.moowork.node

As for publications, there's #10, but as I'm currently the only person actively working on the fork I've not really looked at it.

As for compatibility, I want to finish the backporting before dropping any compatibility and where I work there's a few people still on Gradle 4 so initially it'd probably be Gradle 4.10 as lowest version (to get access to some of the new APIs) but I'm open to the idea of dropping Gradle 4 support a few months later :-)

**Comment by imanushin** [comment]
@deepy , agree with you regarding the minimal version. And yes, there are not collision at gradle.org (sorry for inconvenience).

I'll take a look on publication and return with proposed PR (and build system configuration details)

**Comment by bsautel** [comment]
I think we can close this issue, right?

The two remaining items are in issues #10 and #62.

**Comment by imanushin** [comment]
I think yes.
