### ISSUE TITLE
Overriding --registry using rules npm_publish does not work

### ISSUE THREAD

**Issue by e88z4** [node-gradle/gradle-node-plugin#151]
I am trying to publish my NPM package to my enterprise repository in Artifactory. We have 2 registeries in our Artifactory configuration. 
1. npm-release-local to publish an internal package
2. npm-remote serving as a proxy to https://registry.npmjs.org
3. npm-all as a virtual repo consisting for both npm-release-local and npm-remote

My project has .npmrc which the registry points to npm-all. When I publish my project to my enterprise registry, I have to override with npm-local instead of npm-all. 

```
registry = https://<my.enterprise.url>/artifactory/api/npm/npm-all
```

I have the following setting in my build.gradle file. 

```
plugins {
    id "com.github.node-gradle.node" version "3.0.1"
}

node {
    version = '14.16.0'
    distBaseUrl = "<my.enterprise.url>/nodejs"
    download = true
}

npm_publish {
    args = ['--registry https://<my.enterprise.url>/artifactory/api/npm/npm-release-local']
}
```

My expectation when I run npm_publish, I expect the plugin to override the configuration in my .npmrc (registry = https://<my.enterprise.url>/artifactory/api/npm/npm-all) with the args from my build.gradle file ("--registry https://<my.enterprise.url>/artifactory/api/npm/npm-release-local")

Below is the log when I executed npm_publish rule. 

```
> Task :npm_publish
Caching disabled for task ':npm_publish' because:
  Build cache is disabled
Task ':npm_publish' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'C:\bitbucket\web-apps-hellonodejs\.gradle\nodejs\node-v14.16.0-win-x64\npm.cmd''. Working directory: C:\bitbucket\web-apps-hellonodejs Command: C:\bitbucket\web-apps-hellonodejs\.gradle\nodejs\node-v14.16.0-win-x64\npm.cmd publish --registry https://<my.enterprise.url>/artifactory/api/npm/npm-release-local
Successfully started process 'command 'C:\bitbucket\web-apps-hellonodejs\.gradle\nodejs\node-v14.16.0-win-x64\npm.cmd''
npm notice
npm notice package: web-apps-hellonodejs@0.1.0
npm notice === Tarball Contents ===
npm notice 160B   .gitattributes
npm notice 6.0kB  gradlew
npm notice 956B   Jenkinsfile
npm notice 3.1kB  gradlew.bat
npm notice 602B   src/App.css
npm notice 379B   src/index.css
npm notice 819B   build.gradle
npm notice 439B   settings.gradle
npm notice 1.8kB  public/index.html
npm notice 3.9kB  public/favicon.ico
npm notice 58.9kB gradle/wrapper/gradle-wrapper.jar
npm notice 553B   src/App.js
npm notice 254B   src/App.test.js
npm notice 517B   src/index.js
npm notice 375B   src/reportWebVitals.js
npm notice 246B   src/setupTests.js
npm notice 517B   public/manifest.json
npm notice 862B   package.json
npm notice 3.4kB  README.md
npm notice 5.3kB  public/logo192.png
npm notice 9.7kB  public/logo512.png
npm notice 241B   gradle/wrapper/gradle-wrapper.properties
npm notice 70B    gradle.properties
npm notice 2.6kB  src/logo.svg
npm notice 70B    public/robots.txt
npm notice === Tarball Details ===
npm notice name:          web-apps-hellonodejs
npm notice version:       0.1.0
npm notice package size:  83.2 kB
npm notice unpacked size: 101.7 kB
npm notice shasum:        bda625366ba2a43f67fa2c2677a6968c4e3fb2f5
npm notice integrity:     sha512-5Ud6zi6o7L0bF[...]FRuYrmzWwS+Rw==
npm notice total files:   25
npm notice
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://<my.enterprise.url>/artifactory/api/npm/npm-all/web-apps-hellonodejs

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ga95\AppData\Roaming\npm-cache\_logs\2021-03-03T13_35_25_844Z-debug.log

> Task :npm_publish FAILED
:npm_publish (Thread[Execution worker for ':',5,main]) completed. Took 13.833 secs.
```

When I executed publishing manually without gradle and the plugin, it works as expected. The --registry command line argument override the registry setting in my .npmrc.
```
C:\bitbucket\web-apps-hellonodejs\.gradle\nodejs\node-v14.16.0-win-x64\npm.cmd publish --registry https://<my.enterprise.url>/artifactory/api/npm/npm-release-local
```

Is this a bug in the plugin?

**Comment by deepy** [comment]
When you're testing on the command line each space is a separate argument so if you switch to `--registry", "https://...` it should work.

But my recommendation is to register a task called `npmPublish` and configure that rather than configure the automatic `npm_foo` tasks.

**Comment by e88z4** [comment]
Separating the argument works. 

What is the pro/cons of registering a task named npmPublish versus npm_publish?

**Comment by deepy** [comment]
`npm_publish` is automatically created by the plugin, it doesn't have any `dependsOn` or inputs/outputs https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/github/gradle/node/NodePlugin.kt#L66

the best way is to create one yourself using camelCase name (as one would expect from a gradle build) and add a `dependsOn` on tasks that might need to run before. Like `npmInstall` for example

**Comment by e88z4** [comment]
Hi @deepy, 

Thank you for your clarification. We close this ticket.
