### ISSUE TITLE
ProxySetting.FORCED should unset environment variables related to proxy settings

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#153]
Currently `FORCED` will overwrite _some_ proxy settings and this might end up being confusing if other configuration has been set, so to get the expected result I am thinking we should unset any environment variable that could affect proxy settings before setting ours.

We currently already have a list of known variables https://github.com/node-gradle/gradle-node-plugin/blob/90871839a706cfe0262492091f301afdcfb8d1e4/src/main/kotlin/com/github/gradle/node/npm/proxy/NpmProxy.kt#L11-L21

**Comment by bsautel** [comment]
That makes sense. Either we use the configuration which is present in the environment, either we use our configuration, but not a mix of both of them that can lead to strange behaviors.
