### ISSUE TITLE
Add yarn.lock as input to NpmInstall task

### ISSUE THREAD

**Issue by etiennestuder** [node-gradle/gradle-node-plugin#155]
From the npm docs:
https://docs.npmjs.com/cli/v7/commands/npm-install#description

```
This command installs a package and any packages that it depends on. If the package has a package-lock, or an npm shrinkwrap file, or a yarn lock file, the installation of dependencies will be driven by that, respecting the following order of precedence:

npm-shrinkwrap.json
package-lock.json
yarn.lock
```

Currently, `yarn.lock` is not declared as an input to the [NpmInstall](https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/github/gradle/node/npm/task/NpmInstallTask.kt) task.

**Comment by deepy** [comment]
This has been committed, will make it into the next release

**Comment by etiennestuder** [comment]
Cool. Thanks.
