### ISSUE TITLE
Remove duplicate logic of @Optional and projectFileIfExists from NpmInstallTask

### ISSUE THREAD

**Issue by etiennestuder** [node-gradle/gradle-node-plugin#156]
It does not seem right to have this logic twice. `@Optional` should be sufficient for Gradle to handle it properly.

Also, using `projectFileIfExists` on output fields is problematic on first runs, where the output file will not exist until the task is actually executed (but the inputs/outputs fields are "evaluated" by Gradle before task execution).

**Comment by bsautel** [comment]
Thanks @etiennestuder for this feedback and sorry for my late reply.

I tried to remove the `IfExists` part of the `projectFileIfExists`:
```kotlin
    private fun projectFile(name: String): Provider<File> {
        return nodeExtension.nodeProjectDir.map { it.file(name).asFile }
    }
```
When I run the integration tests in which the optional input files are not present, I get this error:
> \> File '/tmp/junit9014837957492571058/npm-shrinkwrap.json' specified for property 'npmShrinkwrap' does not exist.
\> File '/tmp/junit9014837957492571058/yarn.lock' specified for property 'yarnLockFile' does not exist.

I don't remember exactly, but I think that's the reason we added the `IfExists` in addition to the `@Optional` annotation. The problem may come from the fact that we are using a `Provider`?

Regarding the outputs, I thought that Gradle also took a look at them after the task execution. What are the consequences of our misuse and what should we do to fix that?

**Comment by etiennestuder** [comment]
@bsautel I now understand. In Gradle. `@Optional` on a @FileInput only checks for nullability of the field, and not whether the provided file actually exists or not. Thus, your code is good as it is. Please close the issue. And sorry for the noise.

**Comment by etiennestuder** [comment]
Since I've opened it, I may as well close it again.
