### ISSUE TITLE
Add node.js download progressbar

### ISSUE THREAD

**Issue by imanushin** [node-gradle/gradle-node-plugin#16]
Suggestion: use [Download](https://github.com/michel-kraemer/gradle-download-task) task for npm.exe file requesting.

Why:
* To support progressbar
* To have gradle incremental builds automatically for the target file

**Comment by deepy** [comment]
I'll get back to you in regards to incremental builds, but there should already be a progressbar.
Here's an excerpt from when I tested a windows build:
```
> :nodeSetup > Resolve files of :detachedConfiguration1 > node-v10.15.0-win-x64.zip > 12.48 MB/15.50 MB downloaded
```

**Comment by deepy** [comment]
This appeared for me on Linux too, so closing this, please re-open if you can reproduce the issue
