### ISSUE TITLE
Plugin downloads wrong arch on PPC machine

### ISSUE THREAD

**Issue by akatona84** [node-gradle/gradle-node-plugin#166]
The detection of the architecture is not considering power pc machines.
https://github.com/node-gradle/gradle-node-plugin/blob/7df7dae63044f9364ee3f6a4f328c19a9dceb869/src/main/kotlin/com/github/gradle/node/util/PlatformHelper.kt#L28

**Comment by deepy** [comment]
None of us have access to a power pc machine, but if you can provide what java says for `os.name` and `os.arch` and what the result of `uname -m` is we can easily add it https://github.com/node-gradle/gradle-node-plugin/blob/7df7dae63044f9364ee3f6a4f328c19a9dceb869/src/test/groovy/com/github/gradle/node/util/PlatformHelperTest.groovy#L26-L35

**Comment by akatona84** [comment]
`uname -m` gives you ppc64le, I've asked to check `os.arch` which was the same (ppc64le), but didn't ask to check `os.name` property, it must be `linux` though. Will check just to be sure

**Comment by akatona84** [comment]
Output of:
```
	System.out.println(System.getProperties().get("os.name"));
	System.out.println(System.getProperties().get("os.arch"));
```
is:
```
Linux
ppc64le
```

**Comment by akatona84** [comment]
Thanks for merging!
