### ISSUE TITLE
Use kotlin as plugin language (instead of Groovy)

### ISSUE THREAD

**Issue by imanushin** [node-gradle/gradle-node-plugin#17]
Question to plugin owner: probably it is better to use Kotlin language for plugin next development?

Why:
* It is first-class citizen of Gradle for now
* We can have strong-typed language for:
** Configuration (with IntelliSence at the IntelliJ Idea)
** Plugin development
* It is a bit faster than groovy (because of compilation)

**Comment by deepy** [comment]
I'm all for this, I really really do not enjoy Groovy and would much prefer Kotlin, probably a good target for a 3.x release

**Comment by deepy** [comment]
With Mike's PR this has been solved :tada:

**Comment by bsautel** [comment]
@deepy , maybe we could also rename in this version the package names (`com.moowork`) that were not changed until now to maintain backward compatibility?

**Comment by deepy** [comment]
@bsautel I suspect we broke backwards compatibility on day 1, we can only ever have one plugin applied per project and if both is on the classpath Something Strange™ is happening.

With that said I'm perfectly in support for moving away from the `com.moowork` namespace
