### ISSUE TITLE
Can't figure out how to configure the install task to use yarn instead of npm

### ISSUE THREAD

**Issue by polaroidkidd** [node-gradle/gradle-node-plugin#171]
I've been trying to start managing my projects using gradle (better IDEA integration) and came across this plugin to help me manage my various tasks inside the `package.json` file. 

However, I've had no luck in configuring the plugin to run `yarn install` instead of `npm install`. Is this not supported or am I missing something in the documentation? I see the `YarnInstallTask` but I'm lost on how to properly configure it.

Any pointers would be appreciated. I've been using the [kotlin dsl file](https://github.com/node-gradle/gradle-node-plugin/blob/master/src/test/resources/fixtures/kotlin/build.gradle.kts) for reference

**Comment by deepy** [comment]
Each of the different tasks has a `NAME` connected to them, that's the Gradle task name they get, in the case of [YarnInstall](https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/github/gradle/node/yarn/task/YarnInstallTask.kt#L85) this is just `yarn` so running `./gradlew yarn` should use yarn

**Comment by polaroidkidd** [comment]
It works! Thanks!
