### ISSUE TITLE
Task :nodeSetup cannot set file mode on node binary in WSL, makes incorrect assumption on filename.

### ISSUE THREAD

**Issue by benwynn** [node-gradle/gradle-node-plugin#173]
so, i'm doing a `./gradlew build` on a windows machine using WSL2 Ubuntu install, version 3.1.0 of the node plugin, and i'm getting the following:

```
* What went wrong:
Execution failed for task ':nodeSetup'.
> Could not copy tar entry /home/someuser/.gradle/caches/modules-2/files-2.1/org.nodejs/node/14.17.0/aa372420174fe8e14196aaa83be29a75b9cad922/node-14.17.0-linux-x64.tar.gz!node-v14.17.0-linux-x64/bin/node to '/mnt/c/projects/someproject/.gradle/nodejs/node-v14.17.0-linux-x64/bin/node'.
   > Could not set file mode 755 on '/mnt/c/projects/someproject/.gradle/nodejs/node-v14.17.0-linux-x64/bin/node'.
```

the actual file inside the .gradle/nodejs is node-v14.17.0-win-x64/node.exe

so, somehow one part of the plugin knew enough to go get the windows binary and install it, but didn't tell some other part of the system that thought it was on a linux server and assumed the platform portion of the filename.

**Comment by deepy** [comment]
I've pushed a small utility to master to help troubleshoot this, I'm not getting the same result in WSL, can you try cloning the repository and running `./gradlew runParameterTest`?
