### ISSUE TITLE
npmInstall task defines default but makes not optional

### ISSUE THREAD

**Issue by Mazorius** [node-gradle/gradle-node-plugin#174]
I moved to the 3.1.0 version and got the following issue:

```
A problem was found with the configuration of task ':npmInstall' (type 'NpmInstallTask').
  - Type 'com.github.gradle.node.npm.task.NpmInstallTask' property 'packageJsonFile' doesn't have a configured value.
    
    Reason: This property isn't marked as optional and no value has been configured.
    
    Possible solutions:
      1. Assign a value to 'packageJsonFile'.
      2. Mark property 'packageJsonFile' as optional.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#value_not_set for more details about this problem.
```

From your code I see that you define a default but not set the property as Optional.

Maybe the property should be an optional to use the default?

**Comment by deepy** [comment]
This might be an oversight on our behalf, while doing a local test I met with the same issue but I'm also not certain what the expected result of `NpmInstallTask` is when no `package.json` exists.

I _think_ the expectation here is that if `download = true` and `package.json` does not exist, `nodeSetup` and `npmSetup` should run but `npmInstall` should be skipped.
Currently, if `download = false` and `package.json` is missing, nothing is run (or at least that's what happened in my local test, need to confirm this)

If that sounds good we can probably make running it conditional on whether `packageJsonFile` exists or not

**Comment by Mazorius** [comment]
Hi @deepy ,

I think skipping the install task on behalf of the package.json file would be a good solution.

Thanks in advance,
Ron

**Comment by deepy** [comment]
I'll have a look at this later, but as a workaround for now you can configure the `npmInstall` task and set `enabled = false`

**Comment by Mazorius** [comment]
Thanks a lot!

I created an empty react project for testing. This works for now.

**Comment by b-gyula** [comment]
The `web3j` gradle plugin uses old `node` and `solidity` gradle plugins, that are **only compatible with gradle version 5.x and not 6.x or even 7.x**. If you want to be able to use it with at least version 6.x you need to specifically apply newer version of these plugins: *node 3.1.1 and solidity 0.3.2*
```
id "org.web3j" version '4.8.8'
id "com.github.node-gradle.node" version '3.1.1'
id "org.web3j.solidity" version '0.3.2'
```

**Comment by RailOuy** [comment]
> configure
So may I ask how to configure the npmInstall task and set enabled = false?

**Comment by deepy** [comment]
@RailOuy `tasks.named("npmInstall").configure { enabled = false }`?

**Comment by RailOuy** [comment]
@deepy thanks

**Comment by deepy** [comment]
Just out of curiosity, @RailOuy  is your use-case to only use `NodeTask` or `NpxTask`? (i.e using a local or downloaded node to execute a script)
Because without `packages.json` there's a bunch of things that aren't going to work as expected (and having an empty or almost empty `packages.json` is legitimate)

**Comment by RailOuy** [comment]
> Just out of curiosity, @RailOuy is your use-case to only use `NodeTask` or `NpxTask`? (i.e using a local or downloaded node to execute a script) Because without `packages.json` there's a bunch of things that aren't going to work as expected (and having an empty or almost empty `packages.json` is legitimate)

No,I just want to use web3j to connect to eth node.But the tool includes the package for solidity's usage.So I just want to skip the gradle error when the project is building. @deepy
