### ISSUE TITLE
Automating retrieving colors.xml from artifactory before a build

### ISSUE THREAD

**Issue by ClarkBattle-McFee** [node-gradle/gradle-node-plugin#186]
I'm new to gradle scripting and dont really know where to start to do something simple. There is an android colors.xml in an artifactory repo inside a tarball. All i want to do is configure gradle so that before it builds it gets that file from the repo (if its changed) and copies it to my android module's res/values/colors.xml. I can do most of that with npm install \<repo\> on the command line but dont know where to start automating it. My first stab is this but the npm install line is probably not right. 

    tasks.register('getResourceTokens') {
        doFirst {
            npm install 'https://artifactory-lvs.corpzone.internalzone.com/artifactory/.../token-tester-0.0.7.tgz'
        }
    }
    
    task copyFiles(type: Copy) {
        from '/Users/cbattle/node_modules/.../colors.xml'
        into '/Users/cbattle/Dev/DesignTokenTest/atoms/src/main/res/values'
    }
    
    copyFiles.dependsOn(getResourceTokens)
    preBuild.dependsOn(copyFiles)

This fails on the npm install line, of course.

**Comment by deepy** [comment]
If you want to download a file you're probably looking for something like [gradle-download-task](https://michelkraemer.com/gradle-download-task-download-files-with-progress/)
Combined with a copy from a `tarTree('your/downlosded/File.tgz')`

You could also setup an `IvyRepository`, add it as a dependency, but download task sounds better

**Comment by ClarkBattle-McFee** [comment]
The file is in a secure corporate artifactory repo that requires npm install to fetch it with the proper credentials in my .nmprc file. I do need to run that command, not something else.

**Comment by deepy** [comment]
You can make it a little easier to read by splitting it like this:
```groovy
args = ['install', '--registry', 'https://artifactory-lvs.corpzone.internalzone.com/artifactory/api/npm/your-repository', 'token-tester@0.0.7']
```

There's some more tips in [Artifactory - Using the npm Command Line](https://www.jfrog.com/confluence/display/JFROG/npm+Registry#npmRegistry-UsingthenpmCommandLine)
