### ISSUE TITLE
Drop gradle support for versions older than 4.10

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#19]
With the next major milestone we'll drop support for old gradle versions

**Comment by cdietrich** [comment]
:+1: i assume this will allow us to fix the gradle 6.0 deprecation issues too

**Comment by cdietrich** [comment]
i saw that we already have some support for multiple gradle versions so i extended that pattern in https://github.com/node-gradle/gradle-node-plugin/pull/22

**Comment by deepy** [comment]
2.x has been merged to master
