### ISSUE TITLE
No value has been specified for property 'packageJsonFile'

### ISSUE THREAD

**Issue by Tyler-MDGL** [node-gradle/gradle-node-plugin#191]
./gradlew build

Configure project :app
Project :app => no module-info.java found

Task :app:npmInstall FAILED

FAILURE: Build failed with an exception.

What went wrong:
A problem was found with the configuration of task ':app:npmInstall' (type 'NpmInstallTask').
In plugin 'com.github.gradle.node.NodePlugin' type 'com.github.gradle.node.npm.task.NpmInstallTask' property >'packageJsonFile' doesn't have a configured value.
Reason: This property isn't marked as optional and no value has been configured.

Possible solutions:
> 1. Assign a value to 'packageJsonFile'.
>2. Mark property 'packageJsonFile' as optional.

**Comment by deepy** [comment]
Do you have a `package.json` in the `app` directory?

**Comment by Tyler-MDGL** [comment]
I do not! I assumed one would be generated when the plugin was ran, but I was wrong!
Specifically, What type of value do I assign to packageJsonFile, path/to/package.json or something else?

**Comment by deepy** [comment]
The error is from `NpmInstallTask` not finding a `package.json` in that folder, if you're not going to be using `npm install` then you can disable the task, otherwise just create your `package.json` in that folder.

You can see an example setup here: https://github.com/node-gradle/gradle-node-plugin/tree/master/examples/simple-node/npm

**Comment by Tyler-MDGL** [comment]
I tried creating a package.json file in the app directory and gradle still isn't building. I get the Unresolved reference error. Is there something I need to import into the build.gradle.kts script?

I also tried to place the package.json file in the build subdirectory within the app directory and I get the same result.

**Comment by deepy** [comment]
This functionality works in our tests and we also build the examples successfully
![image](https://user-images.githubusercontent.com/905507/131901764-4af63861-70a9-4590-ac8a-ec03e838d27a.png)

Could you share your repository or create a small test-case repository showing the issue?
