### ISSUE TITLE
Support s390x

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#193]
Copying https://github.com/srs/gradle-node-plugin/issues/379 here:

> Linux on Z system:
> 
> os.arch = s390x
> os.name = Linux
> execute "uname -m" = s390x
> 
> execute "cat /proc/version":
> Linux version 3.10.0-1160.36.2.el7.s390x (mockbuild@s390-037.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Jul 7 22:55:15 EDT 2021
> 
> The node download url, eg, "https://nodejs.org/dist/v6.14.3/node-v6.14.3-linux-s390x.tar.gz", is expected.

**Comment by deepy** [comment]
@mengwan9 I've pushed a branch called `issue-193` which should fix this, the easiest way to test this is probably to clone this repository and checkout that branch and then include this build in a project using this:
https://docs.gradle.org/current/userguide/composite_builds.html#included_plugin_builds

I'm fully booked today but tomorrow I'll have a look at what needs to be fixed before the next release

**Comment by mengwan9** [comment]
@deepy appreciate your fix this. I will verify it with your branch then response you. Thanks~~

**Comment by mengwan9** [comment]
@deepy I have built a new gradle node plugin based on your fix branch issue-193 then make our project refer to the new fixed plugin temporarily. It works and  the project can download a s390x node package.  Thanks!!

**Comment by mengwan9** [comment]
Btw, I have a question about the plugin with early version of gradle. If I apply the newer version of plugin, eg, 3.x, to a gradle 4.7 base project, the error can be thrown:
```
Failed to apply plugin [id 'com.github.node-gradle.node']
   > Could not create an instance of type com.github.gradle.node.NodeExtension_Decorated.
      > org/gradle/api/model/ObjectFactory.directoryProperty()Lorg/gradle/api/file/DirectoryProperty; (loaded from file:/root/.gradle/wrapper/dists/gradle-4.7-bin/73xux3q4721jgr4pjvqf9o30/gradle-4.7/lib/gradle-core-api-4.7.jar by org.gradle.internal.classloader.VisitableURLClassLoader@163a3738) called from class com.github.gradle.node.NodeExtension (loaded from file:/root/testopensource/ by org.gradle.internal.classloader.VisitableURLClassLoader@a4634d91)
```
In other words, does the pluigin have any requirement for project's gradle version?  Because I found it can work well with a gradle 6.x project but 4.x fails as above.

**Comment by deepy** [comment]
At the moment the lowest version we support is Gradle 5, there are earlier releases which would work with older versions but to keep the code-base simple we don't support older versions 

And speed-wise there's great arguments to be made for Gradle 6+ with configuration-cache

**Comment by deepy** [comment]
This is in `3.1.1` which was just released
