### ISSUE TITLE
reading config from .npmrc or .yarnrc

### ISSUE THREAD

**Issue by bwgjoseph** [node-gradle/gradle-node-plugin#196]
Hi,

I couldn't find information about this and like to know if instead of defining registry via task, can it read from the default `.npmrc or .yarnrc` instead?

As mentioned in the [faq](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/faq.md#how-do-i-ignore-some-files-of-the-node_modules-directory-that-are-modified-by-the-build-and-prevent-tasks-from-being-up-to-date-), you can setup like this

```gradle
tasks.npmSetup {
    doFirst {
        args.addAll(['--registry', 'http://myregistry.npm.com'])
    }
}
```

My config has something like

```bash
// .yarnrc
registry "http://artifactory/artifactory/api/npm/orion-virtual-npm/"

// .npmrc
strict-ssl=false
```

If my project root has either (or both) of the config files, why wouldn't it read from there instead?

If it does read, then I might have some configuration issues that needs to be fixed because the last I tried, it does not read from the config files.

Thanks

**Comment by deepy** [comment]
When you say project root you mean your js project root right?
That is, right next to your `package.json` which usually isn't in your gradle project root

Reading from the files should work fine and there's some more information [in the npm docs here](https://docs.npmjs.com/cli/v7/configuring-npm/npmrc) but keep in mind that this plugin relies on a project-local `--prefix` so specifically the global configuration file option from that page is not accessible to you, but the other 3 should work fine

**Comment by deepy** [comment]
Also `npm config list` is a great way of testing this

**Comment by bwgjoseph** [comment]
Hmm, it's a multi-module gradle project. 

So it's something like

```
|--backend
   -- build.gradle
|--frontend
   -- build.gradle
   -- package.json
   -- .npmrc
   -- .yarnrc
--build.gradle
```

What you meant is that even if I don't set the task in `build.gradle`

```groovy
tasks.npmSetup {
    doFirst {
        args.addAll(['--registry', 'http://myregistry.npm.com'])
    }
}
```

It should still work, because it should read from `.yarnrc and/or .npmrc` right?

I probably have to double check again, as I didn't really take note while running on the machine. It was because my `gitlab-ci` failed as it couldn't point to the correct registry after I took out the `npmSetup` task as I thought it would read from the configuration files instead

I don't get you on the project-local `--prefix` portion, could you explain a little bit more for my context? And how does `npm config list` test anything?

Thanks for helping me out

**Comment by bwgjoseph** [comment]
Anyway, I did some additional test, and here's my observation, not sure if it's correct.

I believe `yarn` will use `yarn.lock` to install packages by default even if I don't specify `--frozen-lockfile` if `yarn.lock` exist when running `yarn install`

So I purposely had `yarn.lock` removed, and placed a custom registry (non reachable) in `.npmrc` and let it run. It will complain that it cannot connect the host, and that the host is from what I defined in `.npmrc`. Next, I added back `yarn.lock` that has all the correct package information like such

```log
"@babel/code-frame@7.10.4":
  version "7.10.4"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.10.4.tgz#168da1a36e90da68ae8d49c0f1b48c7c6249213a"
  integrity sha512-vG6SvB6oYEhvgisZNFRmRCUkLz11c7rp+tbNTynGqc6mS1d5ATd/sGyV6W0KZZnXRKMTzZDRgQT3Ou9jhpAfUg==
  dependencies:
    "@babel/highlight" "^7.10.4"
```

And I still have `.npmrc`, now when I run `yarn install --frozen-lockfile`, it will use `yarn.lock` info to pull the packages because that's what I tell yarn to do. So I guess the behavior is correct.

Next, I tried to have `yarn.lock and .npmrc`, but removed `--frozen-lockfile`, and ran. And it still seem to be still using `yarn.lock` where I expect it to install a fresh set based on the registry defined. I print out `yarn config list` and the registry was indeed pointing to `.yarnrc/.npmrc` but not sure why the installation is still running

**Comment by deepy** [comment]
the `npmSetup` task is probably running from the wrong folder 🤦‍♀️
we should probably look into some way of providing general settings from the plugin-side (like `--registry` or `--frozen-lockfile`)

**Comment by bwgjoseph** [comment]
That would be great, but I think ensuring that it respect the .`npmrc/.yarnrc` config is also important as that should be the default.

**Comment by deepy** [comment]
Respecting `.npmrc`/`.yarnrc` is really up to node/yarn themselves and if the file is in the proper place then it's going to get respected, if your proper place is elsewhere there's `--userconfig` to tell `npm` about it

also this is related to #198

**Comment by bwgjoseph** [comment]
Apologies for the delay response.

I thought that was the case as well, but I am unable to determine what is causing the issue where the config file are not being respected. And I am not able to replicate it exactly outside of the existing project. 

Will report back again if I manage to figure out, or replicate it reliably

Thanks!
