### ISSUE TITLE
Documentation for Angular

### ISSUE THREAD

**Issue by ChrTall** [node-gradle/gradle-node-plugin#197]
Can you provide me with some help for configuring the plugin?
I succesfully used it for building a Spring Api with a Angular Frontend.
Now I moved from npm to yarn and I have to adjust the following task:
task buildAngularApp(type: NpxTask) {
  dependsOn npmInstall
  command = 'ng'
  args = ['build', '--prod']
  inputs.files('package.json', 'package-lock.json', 'angular.json', 'tsconfig.json', 'tsconfig.app.json')
  inputs.dir('src')
  inputs.dir(fileTree("node_modules").exclude(".cache"))
  outputs.dir('dist')
}

I changed dependsOn from npmInstall to yarn.
But when I change type:NpxTask to YarnTask I get error messages for command='ng'.

**Comment by deepy** [comment]
The `FooTasks` pretty much get turned into their equivalent commands, so an `NpxTask` with command `ng` would be equal to `npx ng`

I think the easiest way to do this is probably to put the `ng build --prod` into `package.json` and to run it through `yarn run foo`
