### ISSUE TITLE
Support Gradle 6.0

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#2]
Current issue (https://github.com/srs/gradle-node-plugin/issues/316)
====
The `IvyArtifactRepository.layout(String, Closure)` method is scheduled to be removed in Gradle 6.0.
`IvyArtifactRepository.patternLayout(Action)` which replaces it is still incubating

    The IvyArtifactRepository.layout(String, Closure) method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the IvyArtifactRepository.patternLayout(Action) method instead.

Old context (https://github.com/srs/gradle-node-plugin/issues/299)
====
(importing an issue that is dear to me https://github.com/srs/gradle-node-plugin/issues/299)
There is a probability that the Node plugin will be incompatible with Gradle 5.0.

The problem relates to a new dependency resolution behaviour that will be introduced in Gradle 5.0 (see [Gradle documentation](https://docs.gradle.org/4.7/userguide/repository_types.html#sub:supported_metadata_sources)). Now if Gradle cannot find any metadata file (e.g. maven's `*.pom` or `ivy.xml`), it looks just for an artifact by its name. Such a behaviour is used in the Node.js plugin which downloads a Node distribution by declaring the distribution URL as a custom ivy-repository ([source](https://github.com/srs/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/task/SetupTask.groovy#L178)).

But since 5.0 Gradle will not look directly for an artifact by default. Thus the Gradle will not be able to resolve the dependency on Node.js distribution and the build will fail.

The easiest way to fix this is to use the `metadataSources` block as shown in Gradle documentation above (also see #296). But such an API was introduced only in Gradle 4.5 so this change will make the plugin incompatible with older versions of Gradle.

So what do you think about this problem? Is the approach above appropriate or distribution downloading should be reworked in some other way?

**Comment by pioorg** [comment]
There might be more... When I build wtih Gradle 4.10.3, in the console output I see

```
Registering invalid inputs and outputs via TaskInputs and TaskOutputs methods has been deprecated. This is scheduled to be removed in Gradle 5.0. A problem was found with the configuration of task ':ui:npmInstall'.
 - File '/I/had/to/skip/full/path/node_modules/package.json' specified for property '$1' does not exist.
```
Maybe the fix is as simple as in https://github.com/joelittlejohn/jsonschema2pojo/issues/809?

**Comment by deepy** [comment]
@atomfrede do you know if there's anyone from jhipster who'd be interested and suitable for commit access?
There are going to be times when I have less time to work on things and it'd be great to have some more redundancy

**Comment by atomfrede** [comment]
@deepy I am the stream lead of our gradle support, so I could do it maybe. We have updated the plugin for the upcoming 6.x release scheduled for ~spring/summer. But I have not much experience with writing large scale gradle plugins so. What is your roadmap for the plugin, especially how to handle gradle 6 deprecations?

**Comment by cdietrich** [comment]
see also https://github.com/srs/gradle-node-plugin/issues/316

**Comment by deepy** [comment]
I guess we could replace the current fix or add another conditional since the new method came in 5.0 and it'd be great to keep backwards compatibility as long as possible (without it becoming a burden)

@atomfrede The current roadmap is probably the following and likely in this order: #7 (Gradle 6 compatible support for `npm ci` instead of `npm install`), add an option to disable the default task dependencies, and then probably going through the issues posted at srs/gradle-node-plugin and see which others need to be fixed.
This issue (#2) will probably be done the moment someone explicitly asks for this support to be included or when there's a rc of Gradle 6

**Comment by deepy** [comment]
Oh and for javaland, any help with #7 would be awesome, I have a PR with a proposed solution but I'm not entirely happy with some of the drawbacks of it (especially that running `npmCi` alone won't be enough in that case)

**Comment by atomfrede** [comment]
I would propose to have gradle 5 as baseline, as it will be less maintenance burden on everyone involved.

**Comment by deepy** [comment]
Having done some internal surveys where I work and seeing how prominent gradle 3 and 4 is I'd like to propose latest gradle 4 as baseline for the next 3 months and then switching to Gradle 5 as we bump the version to 2.0 and ditch grunt/gulp #12 (while also giving them some time to be marked as deprecated in 1.x)

**Comment by cdietrich** [comment]
@deepy do you have a ETA for a 1.5.2 / 1.6.0 containing this fix?

**Comment by deepy** [comment]
Sorry about the delay, I've been drained from moving two apartments into one, I'll release a 1.5.2 tonight

**Comment by deepy** [comment]
@cdietrich 1.5.2 is now out
