### ISSUE TITLE
NpmInstallTask/YarnInstallTask declares inputs/outputs twice.

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#20]
Really wish I'd noticed this before releasing 1.5.0 but with the backported functionality we now have inputs/outputs declared twice and only one is optional.
Line 28 should have had a `.optional()` at the end.

https://github.com/node-gradle/gradle-node-plugin/blob/4d934b1630b27a63d66739509c556b3a1b5fdd1a/src/main/groovy/com/moowork/gradle/node/npm/NpmInstallTask.groovy#L24-L29

https://github.com/node-gradle/gradle-node-plugin/blob/4d934b1630b27a63d66739509c556b3a1b5fdd1a/src/main/groovy/com/moowork/gradle/node/npm/NpmInstallTask.groovy#L33-L36

**Comment by deepy** [comment]
Thinking about this, isn't `package-lock.json` a `npm install` output?

**Comment by rafeememon** [comment]
@deepy -- I believe `package-lock.json` is both an input and output of `npm install`.  The installed packages will be determined by its contents, and it will be updated if any dependencies are missing ([ref](https://docs.npmjs.com/cli/install#description)).

If we want to make sure all cases are covered, it looks like `npm-shrinkwrap.json` should also be added as an input to the task.

**Comment by deepy** [comment]
Hmm. Yeah, that scenario makes sense, I wonder if gradle will let me have a file as both input and output.
`npm-shrinkwrap.json` is luckily always input (for install/ci) so that's simple to add, thanks 😃

**Comment by cdietrich** [comment]
@deepy now i am getting this error

```
* What went wrong:
A problem was found with the configuration of task ':org.eclipse.xtext.web:npmInstall'.
> File '/data/tmp/xtext-web/org.eclipse.xtext.web/npm-shrinkwrap.json' specified for property '$2' does not exist.
```
any idea?

**Comment by deepy** [comment]
I might've been mistaken here, but that issue should've been in 1.5.1 too, it's sneaky since with Gradle 4 the tests didn't fail, but with Gradle 5 they failed.
There's a fix in the 2.x branch right now (and I'm going to do the finishing touches on 2.x later today)

**Comment by cdietrich** [comment]
interestingly i dont see it in 1.5.1

**Comment by deepy** [comment]
@cdietrich 1.5.3 has been published with the fix

**Comment by cdietrich** [comment]
its working fine for us now. many thanks
