### ISSUE TITLE
make SetupTask use preconfigured Ivy repo it it finds one

### ISSUE THREAD

**Issue by sine-loco** [node-gradle/gradle-node-plugin#21]
If one sits behind bloody enterprise firewalls, the only way to grab NodeJS distr is via mirrored repo, which usually prohibits anonymous access :)
The easiest and most flexible way is to allow dev to configure such a repo in a gradle script.
Now dev has to use nasty workarounds to add credentials to the repo :(

I suggest to add logic to SetupTask#addRepository: it it find distBaseUrl in one of existing repos, it sets that repo into SetupTask#repo field instead of creating new repo.

**Comment by deepy** [comment]
I wonder if we even need to do the repository dance at all in the plugin.
I'm guessing that we'll probably be fine even if we just add the default repo (which should add it at the end), which would let you use preconfigured repos (as they would appear first)

**Comment by deepy** [comment]
I've tested this and I think it should be fine to not clear the repositories, it'll incur a hit on repos listed before but that seems acceptable

**Comment by sine-loco** [comment]
I suppose adding repo unconditionally would be an overkill. I'd suggest to check whether required repo already exists and add new one otherwise.
