### ISSUE TITLE
Can no longer see NpmTask.result

### ISSUE THREAD

**Issue by JamesXNelson** [node-gradle/gradle-node-plugin#237]
It used to be possible to look at the `.result` of an invoked NpmTask, but upon updating to latest version, I see _nothing is recording the returned exec result_
```
    @TaskAction
    fun exec() {
        val command = npmCommand.get().plus(args.get())
        val nodeExecConfiguration =
                NodeExecConfiguration(command, environment.get(), workingDir.asFile.orNull, ignoreExitValue.get(),
                        execOverrides.orNull)
        val npmExecRunner = objects.newInstance(NpmExecRunner::class.java)
        npmExecRunner.executeNpmCommand(projectHelper, nodeExtension, nodeExecConfiguration, variantComputer)
    }
```
please store the result object from executeNpmCommand somewhere visible to buildscripts (on the task), so smart builds that want to inspect errors and make helpful suggestions can do so.

**Comment by deepy** [comment]
The history of why this was removed is in https://github.com/node-gradle/gradle-node-plugin/issues/144

Would the proposed alternative in #144 work for your use-case?
The branch is still around and I've planned to finish and merge it Soon™

**Comment by JamesXNelson** [comment]
Sorry for the complaining before... is there anything I can do to help make this happen?
