### ISSUE TITLE
Is it applicable to TypeScript projects?

### ISSUE THREAD

**Issue by bvn13** [node-gradle/gradle-node-plugin#261]
I tried this task:
```
def buildTask = tasks.register("buildWebapp", NpxTask) {
    command = "tsc"
    //args = ["--outDir", "${buildDir}/webapp/public"]
    dependsOn(yarn)
    inputs.dir(fileTree("src").exclude("**/*.test.js").exclude("**/*.spec.js").exclude("**/__tests__/**/*.js"))
    inputs.dir("node_modules")
    inputs.dir("public")
    outputs.dir("${buildDir}/webapp")
    environment = ["BUILD_PATH": "${buildDir}/webapp/public"]
}
```

but generated `jar` file is empty.

**Comment by deepy** [comment]
Task itself looks ok, I suspect you want to depend on `yarnInstall` instead though

But is your jar configured to get the app from `$buildDir/webapp`? And have you verified that if you run `buildWebApp` the app is built into `$buildDir/webapp`?

**Comment by bvn13** [comment]
I am not familiar with frontend stack.
My issue was that I copypasted option "noEmit=true" into `tsconfig.json` file. After disabling it I saw files built into `$buildDir/webapp` folder. 

So now I have this task:
```
def buildTask = tasks.register("buildWebapp", NpxTask) {
    command = "tsc"
    args = ["--outDir", "${buildDir}/webapp/public/gpx"]
    dependsOn(yarn)
    inputs.dir(fileTree("src").exclude("**/*.test.js").exclude("**/*.spec.js").exclude("**/__tests__/**/*.js"))
    inputs.dir("node_modules")
    inputs.dir("public")
    outputs.dir("${buildDir}/webapp")
    environment = ["BUILD_PATH": "${buildDir}/webapp/public/gpx"]
}
```

And I see this task does not copy `public` folder (was created by `create-react-app`).

Task with command `reaect-scripts`  with args `build` (as described in examples here) did copy `public` folder.

Why do not my task copy `public` folder? Is it because of `tsc` itself? And do I have to write another task just for copying `public` folder?
