### ISSUE TITLE
Can't set distBaseUrl

### ISSUE THREAD

**Issue by florian-renfer** [node-gradle/gradle-node-plugin#309]
Hey there, we're having trouble configuring the distBaseUrl property. No matter which URL we would like to use to fetch the nodejs binaries, it always uses the following URL to the JBoss repo.

Used URL: https://repository.jboss.org/nexus/content/groups/public/org/nodejs/node/20.11.1/node-20.11.1.pom

However the plugin is part of our CI/CD pipeline which constantly fails due to this.

Is there any logical explanation as to why this happens?

We have also looked into the FAQ and existing issues and haven't been able to sort it out.

Our configuration for the plugin:

`node {
    version.set("20.11.1")
    npmVersion.set("10.2.4")
    distBaseUrl.set("https://nodejs.org/dist")
    download.set(true)
}
`

**Comment by DanielSongYu** [comment]
Sorry how did you resolve this issue? Facing the same.
