### ISSUE TITLE
Expose YarnInstallTask and YarnTask group 

### ISSUE THREAD

**Issue by rlsf** [node-gradle/gradle-node-plugin#31]
please expose the groups used by those tasks as constants, so they can be used in new task instances. e.g:
```
val task = tasks.registering<YarnInstallTask>("fooInstall") {
     group = NodePlugin.NODE_GROUP
}
```

**Comment by deepy** [comment]
I'll be adding the groups tomorrow, sorry about the delay, I caught a nasty fever.

Unless anyone has a different opinion on how to group them I'll be adding one group per plugin, so there'll be a yarn group, a node group, etc.

**Comment by deepy** [comment]
I've added a `NODE_GROUP` matching the current usage, in the next major we'll split it into 3 groups: node, nom, and yarn.

**Comment by bsautel** [comment]
@deepy , I introduces three groups (Node, npm and Yarn) in 8a8adbd. Let me know if it is not what you wanted to do.
