### ISSUE TITLE
there is no way to disable progress logs of npm task

### ISSUE THREAD

**Issue by vladbakumenko** [node-gradle/gradle-node-plugin#312]
When you run the npm_run_build command, a lot of build logs are displayed in the console. Is it possible to hide them?
![image](https://github.com/node-gradle/gradle-node-plugin/assets/34581079/85026ac4-d337-4c51-8544-d1fe00454b8c)

**Comment by deepy** [comment]
At a glance it looks like webpack thinks it's running in an interactive terminal by mistake, I'd start by looking at webpack's configuration

But there's nothing connecting the log systems, so from this plugin's perspective you could hide standard out or standard err, or both
Only showing stderr will probably get you most of the important information, but in general this is best configured downstreams (in this case in webpack)

**Comment by deepy** [comment]
I guess there's also the option of filtering lines that include `[webpack.Progress]`

**Comment by vladbakumenko** [comment]
thanks for response!
