### ISSUE TITLE
Fix configuration cache incompatibility

### ISSUE THREAD

**Issue by nbrugger-tgm** [node-gradle/gradle-node-plugin#326]
This plugin is not compatible with gradle configuration cache:
```
 - Task `:webpage:npmInstall` of type `com.github.gradle.node.npm.task.ConfigurableNpmInstallTask`: invocation of  'Task.project' at execution time is unsupported.
   See https://docs.gradle.org/8.10.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

Would you accept a contribution (or fix it yourself?)

**Comment by nbrugger-tgm** [comment]
I just saw it seems to be present in [3.0.0-rc7](https://github.com/node-gradle/gradle-node-plugin/releases/tag/3.0.0-rc7)

**Comment by deepy** [comment]
I don't know where you're getting `ConfigurableNpmInstallTask` from but I can't find it in the repository's history, and having just tested 7.1.0 I am not getting any configuration-cache errors

Can you create a sample project that reproduces the issue with `7.1.0`? I can't accept patches for 3 year old versions

**Comment by nbrugger-tgm** [comment]
Oh i see. Good catch. Someone checked in a cloned & modified version of NpmInstallTask that fixed a bug or something long ago (`ConfigurableNpmInstallTask`) hence it wasn't up-to-date and still containing the project access.

I am sorry for the inconvenience and the misinformation. (I got a bit too used to plugins not being compatible)

**Comment by deepy** [comment]
Awesome, thanks :-)

And while I might be slower at responding than usual, we're always open for PRs and feature requests (feature requests moving _very_ slowly at the moment)
