### ISSUE TITLE
Run tests with multiple gradle versions

### ISSUE THREAD

**Issue by deepy** [node-gradle/gradle-node-plugin#4]

**Comment by sine-loco** [comment]
Could you please specify what do you mean by 'multiple versions'? 5.0-5.6 version range?

**Comment by deepy** [comment]
The Gradle testkit lets you specify what version to use https://docs.gradle.org/current/userguide/test_kit.html#sub:gradle-runner-gradle-version

We're not really making use of that currently in the tests and this issue is about rewriting them to make use of that functionality :-)
