### ISSUE TITLE
configure YarnInstallTask parameters on task level

### ISSUE THREAD

**Issue by rlsf** [node-gradle/gradle-node-plugin#42]
YarnInstallTask parameters (pacakges.json, yarn.lock, node_modules) are configured based on NodeExtension.nodeModulesDir, which means they are the same for any task executed in a given project. 
it would be beneficial to decouple this connection, so their values can be set per task instead.

**Comment by bsautel** [comment]
Hello @rlsf . Thanks for this issue report.

I think I don't understand what you are talking about exactly. Could you give us an example in which you would need them to be decoupled?

**Comment by deepy** [comment]
If we make the configuration lazy passing the parameters to the task would make sense.

That'd let someone create ad-hoc Yarn/NpmInstalls that don't necessarily conform to the plugin, which I guess is mainly useful if you have multiple un-related builds in the same project.
Perhaps a scenario where you got some `src/appA/packages.json`, `src/appB/packages.json` and want to build them in the same project but independently?

**Comment by bsautel** [comment]
Ok, I see what you mean.

`NpmInstallTask` is a `NpmTask` that defines the `install` command and the inputs / outputs. It is also true for yarn.
If I want a npm install task in a given directory, I can do that:

```groovy
task npmInstallAppA(type: NpmTask) {
    args = ['install']
    workingDir = file("src/appA")
    inputs.file("src/appA/package.json")
    // other inputs
    outputs.dir("src/appA/node_modules")
    }
```

Would this be an acceptable workaround?
