### ISSUE TITLE
Gradle 6 deprecation warnings

### ISSUE THREAD

**Issue by boris-petrov** [node-gradle/gradle-node-plugin#43]
Running both the `yarnSetup` and `yarn` tasks under Gradle 6 yields the following warnings:

```
> Task :frontend:yarnSetup
Property 'runner.execOverrides' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'runner.workingDir' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

**Comment by bsautel** [comment]
Gradle 5 checks the same thing when building a plugin and until recently we had multiple warnings telling that the task inputs are not correctly defined.
I recently did several changes regarding the tasks inputs declaration and there is no longer any warning of this kind at compile time.
I just come to check with Gradle 6 and I confirm that these warnings disappeared with the current `master` version (to be released).

**Comment by bsautel** [comment]
I just come to push a commit that makes all integration tests to run also on Gradle 6.0-rc-1 to ensure the plugin (at least all the tested features of the plugin) works with Gradle 6.
