### ISSUE TITLE
How can I fetch yarn from a local mirror?

### ISSUE THREAD

**Issue by dusan-turajlic** [node-gradle/gradle-node-plugin#64]
I see its possible to specify a `distBaseUrl` for Node.js but not for yarn. Am I missing something or is that just not possible at the moment?

**Comment by bsautel** [comment]
Hello @dusan-turajlic.

Node.js is downloaded by default from [the official repository](https://nodejs.org/dist/). It is bundled with npm.

Yarn is installed using npm using a kind of `npm install --global yarn`.

To do what you want, it would be probably necessary to use another npm registry.

Why do you want to use another download repository / registry?

**Comment by dusan-turajlic** [comment]
@bsautel We try not to depend on any third-party dependencies like npm's registry. So we can have a consistent and reliable build environment.

**Comment by dusan-turajlic** [comment]
@bsautel Do you have any solution for me that would work the way I want? Or do I need to extend your plugin in my project and add support for connecting to a local different registry?

**Comment by deepy** [comment]
@dusan-turajlic does your repository (nexus, artifactory, etc) support mirroring npm?
If so just follow their instructions for setting it as your registry

**Comment by dusan-turajlic** [comment]
@deepy Cool. We are not currently using a mirror but we are evaluating different artifactory currently so once we have chosen one I will do the method you suggested until then we will use the official npm registry
