### ISSUE TITLE
Consider supporting pnpm

### ISSUE THREAD

**Issue by bojanraic** [node-gradle/gradle-node-plugin#67]
**pnpm** is a fast, disk space efficient package manager relying on hard links and symlinks to save only **one copy** of a module/version **regardless of how many projects you have using the same version of a module or library**. Read more about it at https://pnpm.js.org/

As someone who experiments a lot, I have dozens of projects using same versions of libs/modules and the disk space used across all node_modules directories for all those projects adds up fast. 

It would be nice to add support for pnpm through a config flag so that developers could choose to make use of it in local builds.
Thanks!

**Comment by deepy** [comment]
You can definitely support this by creating `NodeTasks`.
I skimmed the page and I suspect it might not work as a drop-in replacement with our inputs/outputs, but I might be wrong.

**Comment by bojanraic** [comment]
Thanks for the quick reply. Gee, I haven't thought of that! In my simple case, I ended up using an NpxTask, but you're absolutely right, at least for now my basic use case is fulfilled. 
I'll leave the issue open if you prefer to do more investigation on drop-in replacement compatibility, otherwise, please feel free to close it. 
Once again, thanks for the suggestion!

**Comment by deepy** [comment]
Native support for pnpm is available in 3.4.0

**Comment by deepy** [comment]
cc @langrp @DreierF
