### ISSUE TITLE
NpmSetupTask does not work when using separate http and https proxy settings

### ISSUE THREAD

**Issue by jcarlstedt** [node-gradle/gradle-node-plugin#69]
We have separate proxy configurations for http and https configured in the user specific gradle.properties 
i.e.
```
systemProp.http.<param>  = value
..
systemProp.https.<param> = value
..
```

NpmSetupTask.kt only passes --proxy or --https-proxy as an argument to node.exe rather than both arguments, which causes npm fetches to fail when separate proxy configurations are used for http and https.

The issue can be worked around by adding the following to the build.gradle file to introduce the missing argument (although holding usernames and passwords in build.gradle is not a way forward).

```
afterEvaluate() {
    npmSetup.args += ['--proxy http://<username>:<password>@<host>:<port>']
}
```

**Comment by bsautel** [comment]
Thanks @jcarlstedt for the pull request. It is now integrated to the 2.2.3 version that just comes to be released.
