### ISSUE TITLE
Add Gradle 6-compatible support for npm_ci

### ISSUE THREAD

**Issue by stefanneuhaus** [node-gradle/gradle-node-plugin#7]
In our projects we favor `npm ci` over `npm install` which is why we applied the following:
```
// use "npm_ci" instead of "npmInstall"
npm_run_build.dependsOn.remove("npmInstall")
npm_run_build.dependsOn("npm_ci")
npm_ci.dependsOn(npmSetup)
```

Since Gradle 5.0 removing a task dependency has been deprecated. And starting with Gradle 6.0 the feature will be removed: [Gradle 5.0 Release Notes - Removing dependencies from a task](https://docs.gradle.org/5.0/release-notes.html#removing-dependencies-from-a-task)

The request is to have a Gradle 6-compatible support for "npm_ci".

Options that come to my mind:
1. Provide a plugin extension property to allow for making the choice. Also provide "npmCi" as a first class citizen task (`NpmCiTask`).
2. Do not add the dependency of the "run" tasks to the "npmInstall" task.

For convenience reasons option 1 would be my preferred choice. If you are fine with this I'd be happy to provide a PR.

There is also a somehow related PR #5 which provides the "NpmCiTask".

**Comment by deepy** [comment]
Would you be interested and able to make a code review of #5?
It's the simplest solution I can think of for this problem and this is an issue I'd really like to solve, but I'm torn between the solutions available, all of them have some drawback that I'm not comfortable with committing to

**Comment by stefanneuhaus** [comment]
@deepy Sure, I'm happy to do the review. I provided some feedback to your PR. Do you see any issues with the proposed solution?

**Comment by deepy** [comment]
I really like the idea proposed here
https://github.com/srs/gradle-node-plugin/issues/307#issuecomment-479085930 but I'm in fever-brain mode right now.
@atomfrede what do you think of going with this approach, releasing it on 1.x and then starting 2.x?

**Comment by deepy** [comment]
This is available in 1.4.0

**Comment by atomfrede** [comment]
@deepy Will integrate it into the our https://github.com/jhipster/generator-jhipster build this week.

**Comment by deepy** [comment]
Upon rolling this out internally I met with a corner-case that needs a fix, will release a patch tomorrow hopefully.
But the issue is that if you define a task named `npm_install` it'll get handled differently than the `npmInstall` task that's added by default, I'm guessing that `npm_install` should be the *same* task as `npmInstall` but I need to test that first

**Comment by cdietrich** [comment]
@deepy do you have a ETA for a 1.5.2 / 1.6.0 containing this fix?
