### ISSUE TITLE
Groovy DSL issue with execOverrides and nodeModulesOutputFilter properties

### ISSUE THREAD

**Issue by cmuchinsky** [node-gradle/gradle-node-plugin#72]
With version 2.2.1 a task similar to this works fine, however with 2.2.2 I'm getting errors related to the `execOverrides`:

`java.io.File cannot be cast to kotlin.Unit` for the first override
`java.io.FileOutputStream cannot be cast to kotlin.Unit` for the second

```
task foo(type: NodeTask) {
    def inputFiles = fileTree('src/main/resources').include("foo.yaml")
    def outputFile = file("$buildDir/bar.yaml")
    def workingDir = file("$buildDir/tmp")
    dependsOn npmInstall
    script = file('node_modules/somenodebinary')
    args = [
      ...
    ]
    inputs.files inputFiles
    outputs.file outputFile
    execOverrides {
      it.workingDir = workingDir
      it.standardOutput = new FileOutputStream(outputFile)
    }
    doFirst {
      ...
    }
  }
```

**Comment by henrik242** [comment]
Just experienced the same thing.  A workaround is to add `null` at the end of the closure:

    execOverrides {
      it.workingDir = workingDir
      it.standardOutput = new FileOutputStream(outputFile)
      null
    }

**Comment by bsautel** [comment]
This regression is due to an error in the release process. The 2.2.2 release should be a fix-only release and it integrated all the changes applied to the master branch, including the Kotlin rewrite that breaks backward compatibility (see #80).

We are going to release a new 2.2.3 version which won't include this issue. But this issue is still valid for the development branch and is probably due to the Kotlin rewrite.

**Comment by bsautel** [comment]
I added some tests to ensure that @deepy 's pull request #73 works. See my comment there, it does not fully work.

@cmuchinsky there is a `workingDir` option for the `NodeTask` that is able to set the working directory without using the `execOverrides` advanced configuration property. But there is no shortcut for the standard output, so you have to use `execOverrides` for that.

**Comment by bsautel** [comment]
I found a solution that works in both Groovy DSL and Kotlin DSL but it is not the recommended way.

Gradle recommends plugins developer to use the `Action` type. The Groovy and Kotlin DSL ensure lambdas are correctly mapped to `Action` types. But it does not seem to work when assigning a value. Generally, in Gradle, we use actions as a parameter of a method, and it is not what we do here.

If someone has a better solution, please help me!

The current code is visible in pull request #90.

**Comment by deepy** [comment]
I'll have a look later on and see if I can find something, I guess the methods in question are the ones like this?
` setExecOverrides(execOverrides: Closure<ExecSpec>)`

**Comment by bsautel** [comment]
Yes, exactly, it is present in multiple tasks. There is also the same issue with the `setNodeModulesOutputFilter` for `NpmInstallTask` and `YarnInstallTask`.

**Comment by bsautel** [comment]
It sounds like I found a better way of handling these properties. See 4f4233cae97ce149feb6b7d42b077fd41bc7ebaa.
