### ISSUE TITLE
Build is failing with gradle version 3.6.0

### ISSUE THREAD

**Issue by monowar1993** [node-gradle/gradle-node-plugin#74]
I have updated my android studio 3.6 and gradle to 3.6.0. But my build is failing on 

> yarnInstallTask

```
idea.project.settings {
  taskTriggers {
    project.getTasksByName('yarn_install', true).forEach { yarnInstallTask ->
      beforeSync yarnInstallTask
    }
  }
}
```

It gives me the following error

```
Build file '$PATH_TO_ROOT_PROJECT/build.gradle' line: 59
A problem occurred evaluating root project 'PROJECT'.
> A problem occurred configuring project ':app'.
   > Failed to notify project evaluation listener.
      > com.android.build.gradle.tasks.PackageAndroidArtifact.getOutputDirectory()Ljava/io/File;
      > KotlinJvmAndroidCompilation with name 'debug' not found.
```

**Comment by deepy** [comment]
Gradle 3.6.0 is pretty old, have you looked at upgrading? There's amazing improvements in each major.
(And the last Gradle 5 is over a year old!)

The latest version of the plugin does not support Gradle 3, but you might be able to run with one of the older versions, I'd start at 1.3.0 and upgrade until it stops working.

But Gradle 3 is unsupported so I highly recommend upgrading Gradle.

**Comment by monowar1993** [comment]
Sorry. Maybe I am misleading you. I am talking about android studio gradle build tools 3.6.0. This build tools uses gradle version 5.6.4. So when I updated my android studio and android studio gradle build tools today android studio is falling to run yarnInstallTask.

**Comment by deepy** [comment]
Ah, that makes sense, 5.6.4 is perfectly ok.

Though it doesn't seem like the failure is related to this plugin.

The error you're getting is likely not from `yarn_install` failing, but rather from your entire build failing, likely from some plugin that hasn't been updated. I'd google the last line of the error message, there seems to be some hints on the web on how to resolve it.

**Comment by monowar1993** [comment]
Thanks for pointing me to the real cause. My problem is solved.
