### ISSUE TITLE
How to add arguments to npm install?

### ISSUE THREAD

**Issue by myronu** [node-gradle/gradle-node-plugin#77]
I'm trying to add arguments to the NPM install command. How do I do that? I tried

`npmInstallCommand = 'install --no-package-lock'`

However, that gives an error "Usage: npm <command>" which means that the command line arguments are wrong.

If I run with --info and paste the same command into the terminal it runs without error.

**Comment by deepy** [comment]
What you're looking for is `args` on `npmInstall` see: [adding arguments](https://github.com/node-gradle/gradle-node-plugin/blob/master/docs/faq.md#how-do-i-set-log-level-for-npm-install-task)

**Comment by 21region** [comment]
I cannot add arguments in `gradle.build.kts`:

![image](https://user-images.githubusercontent.com/3749557/76424312-1f183080-63b9-11ea-8430-6eb8e39aaf32.png)

**Comment by deepy** [comment]
That's strange, which version are you using? in the kotlin version args is a var and in the groovy version it should be equivalent.

I guess you could try `args.add()`

**Comment by 21region** [comment]
I use kotlin `1.3.61` and `gradle-node-plugin` `2.2.3`.
By the way, `options` field works as expected
![image](https://user-images.githubusercontent.com/3749557/76429509-360e5100-63c0-11ea-84bb-287ec50e444e.png)

**Comment by deepy** [comment]
Ah my bad, args is not public in the groovy version but it does have a setter `setArgs( final Iterable<?> value )` and `addArgs( final Object... args )`

`options` probably works because it's an `Iterable<?>` whereas `args` is `List<?>`, so `setArgs(listOf())` probably works

**Comment by bsautel** [comment]
We will be able to write `args = listOf()` in the Kotlin DSL with version 3.0.

**Comment by dailytabs** [comment]
Feels silly that we have to use the `npmInstallCommand` option (to use `ci`) and separately customize the task to add arguments. We should be able to do both in the same place, either like the OP expected (as well as most users) or in the task by giving us access to a command property (which would deprecate the need for the option):

```groovy
tasks.named('npmInstall') {
    command = System.getenv('CI') ? 'ci' : 'install'
    if (System.getenv('CI'))
        args = ['--cache', '.npm', '--prefer-offline', '--no-audit']
}
```
