### ISSUE TITLE
Hot to use this plugin with build.gradle.kts

### ISSUE THREAD

**Issue by MBurchard** [node-gradle/gradle-node-plugin#78]
In a new project I want to user the plugin but with Kotlin instead of Groovy.

	plugins {
		id "com.github.node-gradle.node" version "2.2.1"
	}
	node {
		version = '12.16.1'
		yarnVersion = '1.22.0'
		download = true
	}
	task yarnBuild(type: YarnTask, dependsOn: 'yarn_install') {
		args = ['build', '--mode', 'development', '--modern']
	}
	task yarnBuildProd(type: YarnTask, dependsOn: 'yarn_install') {
		args = ['build', '--modern']
	}
	yarn_install.dependsOn(yarn_cache_clean)

This is the working Groovy code.
The documentation states: "All yarn command can also be invoked using underscore notation based on a gradle rule".
But Kotlin does not know yarn_install...

	import com.moowork.gradle.node.yarn.YarnTask

	plugins {
		id("com.github.node-gradle.node") version "2.2.1"
	}
	node {
		version = "12.16.1"
		yarnVersion = "1.22.0"
		download = true
	}
	tasks.create<YarnTask>("yarnBuild") {
		dependsOn("yarn_install")
	}
	tasks.create<YarnTask>("yarnBuildProd") {
		dependsOn("yarn_install")
	}
	yarn_install {
		dependsOn(yarn_cache_clean)
	}

build.gradle.kts:17:1: Unresolved reference: yarn_install

Besides that I don't found out how to provide the args properly.

**Comment by deepy** [comment]
Well this one caught me by surprise too, the yarn install task is named just `yarn`, but on the bright side everything seems to work fine.

```kotlin
tasks {
    named<YarnTask>("yarn") {
        args = listOf("hello", "is it me you're", "looking for")
    }
}
```

```
> Task :yarn FAILED
yarn install v1.22.0
info No lockfile found.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add hello is it me you're looking for" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by MBurchard** [comment]
Thank you very much with this hin, it works this way...

	tasks {
		named<YarnTask>("yarn_install") {
			dependsOn("yarn_cache_clean")
		}
	
		create<YarnTask>("yarnBuild") {
			dependsOn("yarn_install")
			args = listOf("build", "--mode", "development", "--modern")
		}
	
		create<YarnTask>("yarnBuildProd") {
			dependsOn("yarnInstall")
			args = listOf("build", "--modern")
		}
	}
