### ISSUE TITLE
Release a 2.2.3 version from the 2.x branch and not from the 3.x branch as for the 2.2.2 version

### ISSUE THREAD

**Issue by bsautel** [node-gradle/gradle-node-plugin#80]
The 2.2.2 version was released from the master branch (which contains the Kotlin rewrite). It breaks the backward compatibility, it's the reason why multiple regressions are reported (#72 or #76).

We should release a 2.2.3 based on the 2.x branch including a cherry-pick of #68 that was added to the 2.2.1, but not all the Kotlin rewrite.

@deepy, I am going to make the cherry-pick of #68 to the of the 2.x branch. I'll tell you when it's done.

**Comment by bsautel** [comment]
@deepy I prepared the release in the 2.x branch. I backported the #68 and #69 fixes (I added the #69 one since you accepted it).

**Comment by henrik242** [comment]
@bsautel Do you plan on releasing the 3.x branch anytime soon? It works well here (except for those two issues, which we have mitigated), and we have a pretty large multi project.

**Comment by bsautel** [comment]
Glad to hear it works not so bad!

This version will break backward compatibility (because of Kotlin rewrite). And we want to take advantage of the opportunity to change other things that require a compatibility break. Here are a few tasks I think about:

- Change the main package name (inherited from the original fork, it does no longer make sense, we probably should use the same as the plugin identifier)
- Use the Gradle lazy configuration API to avoid instantiating tasks if they are not executed (#39). We were waiting for the Kotlin rewrite because it requires a refactoring for which static typing will be really helpful.
- We probably should also upgrade the default Node.js version from 10.x to 12.x (current LTS branch)
- Try to fix the 2 issues you are talking about
- Write a small 2.x to 3.x migration guide

**Comment by deepy** [comment]
My bad, I'd tested the kotlin rewrite with a few different project and while that and the test suite worked fine that obviously didn't catch nearly enough.

2.2.3 is available on the plugin portal now

**Comment by bsautel** [comment]
Thanks @deepy for the release. I cherry picked the 2.2.3 release commit to the master branch so that the README from the master branch shows the right production version to use.

Have a nice week-end!

**Comment by henrik242** [comment]
@bsautel How about releasing a 3.x milestone version or something? It would be nice to follow the kotlin version of this.

Then I wouldn't have to do ...

                setExecOverrides(closureOf<DefaultExecAction> {
                    setIgnoreExitValue(true)
                    standardOutput = reportFile.outputStream()
                })

... anymore.  With the 3.x branch I can do this instead.

                execOverrides = {
                    isIgnoreExitValue = true
                    standardOutput = reportFile.outputStream()
                }

**Comment by deepy** [comment]
We can probably fix that in both editions, we were previously only accepting a `Closure<ExecSpec>` when we should've moved to `Action<ExecSpec>` see: #73
