### ISSUE TITLE
Error Calling npm_run_build or npm_install inside of register task of configuration avoidance api of gradle

### ISSUE THREAD

**Issue by exploiz65** [node-gradle/gradle-node-plugin#83]
Hello when i try to run npm tasks inside of a register task in gradle. I try to use the configuration avoidance api of gradle. And we have following snippet:
this is not working:
   project.tasks.**register**('NodeBuild') {

       dependsOn project.tasks.npm_run_build, project.tasks.npm_test

      }

But this is working when running in create:

   project.tasks.**create**('NodeBuild') {

       dependsOn project.tasks.npm_run_build, project.tasks.npm_test

      }

I get the following error when using register:

> Could not create task ':NodeBuild'.
          > DefaultTaskContainer#create(String, Class) on task set cannot be executed in the current context.

Can someone please help me.

**Comment by deepy** [comment]
This is because up until NodeBuild is resolved Gradle doesn't know that it'll have to create the task, you could work around this also by doing (anywhere)
```groovy
tasks.named("npm_run_build")
tasks.named("npm_test")
```
To force Gradle to create these, though in general I'd probably register tasks on my own if they're permanent rather than relying on the ones generated by rules.
e.g. I got a 
```groovy
tasks.register("npmRunDist", NpmTask) {
    args = ['run', 'dist']
    dependsOn tasks.named("npmInstall")

    outputs.dir file("dist")
    inputs.dir file("src")
    inputs.file("webpack.prod.js")
    // some additional inputs too
}
```

**Comment by exploiz65** [comment]
i tried your solution also.. there i get the same error.....

**Comment by deepy** [comment]
Which one of them?
I'd recommend the latter, creating specific tasks that you are interested in, but if your NodeBuild only depends on node tasks then using create instead of register should be fine as the node tasks aren't lazy (yet)
