### ISSUE TITLE
How to run NpmInstallTask behind proxy?

### ISSUE THREAD

**Issue by 21region** [node-gradle/gradle-node-plugin#84]
Here is error we get, when we run the build

```
14:16:42  > Task :admin-tool:npmInstall
14:31:52  npm ERR! code ETIMEDOUT
14:31:52  npm ERR! errno ETIMEDOUT
14:31:52  npm ERR! network request to https://registry.npmjs.org/@babel/plugin-syntax-top-level-await/-/plugin-syntax-top-level-await-7.8.3.tgz failed, reason: connect ETIMEDOUT 104.16.26.35:443
14:31:52  npm ERR! network This is a problem related to network connectivity.
14:31:52  npm ERR! network In most cases you are behind a proxy or have bad network settings.
14:31:52  npm ERR! network 
14:31:52  npm ERR! network If you are behind a proxy, please make sure that the
14:31:52  npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
14:34:00  
14:34:00  npm ERR! A complete log of this run can be found in:
14:34:00  npm ERR!     /home/jenkins_node/.npm/_logs/2020-03-12T11_29_23_391Z-debug.log
14:34:00  
14:34:00  > Task :admin-tool:npmInstall FAILED
14:34:00  
14:34:00  FAILURE: Build failed with an exception.
14:34:00  
14:34:00  * What went wrong:
14:34:00  Execution failed for task ':admin-tool:npmInstall'.
14:34:00  > Process 'command '/home/jenkins_node/node_root/workspace/wfm_build_wardev/Server/admin-tool/.gradle/nodejs/node-v13.10.1-linux-x64/bin/npm'' finished with non-zero exit value 1
14:34:00  
```

**Comment by deepy** [comment]
I'm going to add a FAQ entry about this, but you want to have the system properties `http(s).proxy` and possibly `.port` set as we give `npm` proxy settings through `System.getProperty("$proxyProto.proxyHost")`

**Comment by deepy** [comment]
Something like this for `gradle.properties` and it should work, though you might want to mirror node locally and make use of `distBaseUrl`
```properties
systemProp.http.proxyHost=igw.xd.cm
systemProp.http.proxyPort=8080
systemProp.http.nonProxyHosts=*.xd.cm|*.local
systemProp.https.proxyHost=igw.xd.cm
systemProp.https.proxyPort=8080
systemProp.https.nonProxyHosts=*.xd.cm|*.local
```

**Comment by 21region** [comment]
Still doesn't work.
It looks like the only place, where proxy is used is an `NpmSetupTask` and it is SKIPPED during build

```
12:27:28  > Task :admin-tool:kaptGenerateStubsKotlin
12:27:30  > Task :admin-tool:kaptKotlin
12:27:42  > Task :admin-tool:compileKotlin
12:27:42  > Task :admin-tool:compileJava NO-SOURCE
12:27:42  > Task :admin-tool:processResources NO-SOURCE
12:27:44  > Task :admin-tool:nodeSetup
12:27:44  > Task :admin-tool:npmSetup SKIPPED
12:28:17  > Task :admin-tool:npmInstall
```

**Comment by deepy** [comment]
Hmm, maybe we should move the proxy part to `NpmTask`.
I guess in situations like this your CI environment ought to have either the proxy settings in `.npmrc` or settings to use a local registry.

You can work around this by configuring  `NpmInstall` and adding the result of `NpmSetupTask.proxySettings()` to `args`

**Comment by imanushin** [comment]
As workaround - just update you build.gradle.kts:

```
val npmRepositoryRedirect = listOf("--registry",
    "https://internal-nmp-report/",
    "--strict-ssl",
    "false")


tasks {
    withType<NpmTask> {
        doFirst {
            args += npmRepositoryRedirect
        }
    }

    withType<NpmSetupTask> {
        doFirst {
            args += npmRepositoryRedirect
        }
    }
}
```

**Comment by deepy** [comment]
@bsautel I think we should probably consider adding this for 3.x, given recent experiences with Big Corp acquiring Smaller Corp Without A Hundred Internal Proxies and in general this plugins role: adding proxy settings where possible is probably the expected result.

**Comment by deepy** [comment]
On the bright side, Yarn and npm both seem to use `--https-proxy` and `--proxy` so that simplifies that.
`npx` however doesn't seem to accept any proxy settings :-(

**Comment by bsautel** [comment]
You mean that when a proxy is configured in the Gradle properties, we should automatically add it to the npm command whenever it is possible?

**Comment by deepy** [comment]
Yes, we currently do it in only one case and in npm, we should do it everywhere in npm and yarn

**Comment by bsautel** [comment]
I refactored the code to get the code that computes the CLI args to add to the `npm` command reusable. I also added some unit tests.

For `npmInstall` and `yarn` tasks, I think I know where to add these args. But where should we add these arguments with a `NpmTask` or a `YarnTask`? Don't really know what to do.

Also, for now, the code works only if you define proxy host and proxy port. Shouldn't be proxy port optional?

I have never used such proxy so I don't know how it works very well and I don't know how to test that our code works.

**Comment by deepy** [comment]
I think that might be just be the way Gradle expects it.

As for proxy settings, it's part of [npm configuration](https://docs.npmjs.com/misc/config#https-proxy) so it should work anywhere. As for yarn, that seems to be the same.

And as for testing, I'll see if I can get one working with wiremock's junit rule.

**Comment by bsautel** [comment]
Ok, and it sounds like the proxy parameters can be placed anywhere. So I am going to add them automatically at the beginning of the args list for both `npm` and `yarn` commands. For `npx`, it does not seem to work.

And as far as I understood, the proxy configuration will only work for network requests done by npm. For instance if you use `npm run somecommand` and `somecommand` makes network calls, it sounds like the proxy will not be taken into account.

**Comment by bsautel** [comment]
@deepy, that's done in master for `NpmTask` and `YarnTask` (and their inheritance children). I did not change the `NpxTask` since the command does not seem to support it.
I added some unit tests to ensure that the proxy args are added at the right place.

**Comment by deepy** [comment]
`npx` not supporting proxy declarations through `--proxy` is sad, but looking at their repository it doesn't seem like it's supported now that zkat no longer works on it.
So while it's super-cool and we for sure want to keep `NpxTask` I don't think we'll be able to get proxy support for it, unless we write a `npmrc` and use `--userconfig` but at that point I feel like it's reasonable to ask the user to enter their proxy settings into `.npmrc` on their own

**Comment by deepy** [comment]
Memory is not serving me, the proxy support (we want) in WireMock seems to be only for WireMock standalone and that's kinda bothersome to set up for the tests.

**Comment by deepy** [comment]
So there's a final annoyance in here, java doesn't let you specify if the proxy is http or https whereas `npm` is given (expecting?) an URL.

So the http request we're dealing with might be handled by a proxy server that only listens on `HTTPS` 🤦‍♀️

There's also `http.nonProxyHosts` and `https.nonProxyHosts` in Java and in npm there's only a `noproxy` setting, but handling that should be as simple as splitting on `|` in both Java strings, adding the results to a set, joining by `,` and `-c noproxy=that`.

And then we get to yell at the people who  are in an environment where there's different proxies for HTTP  and HTTPS and they have different `nonProxyHosts` since I don't think there's any way for us to support that sensibly.

For sanity I think we should add a feature toggle to the proxy settings as in its current state it seems unlikely that this with its current implementation would work for anyone in a corporate environment. Maybe we should add even more toggles or settings for proxying?

**Comment by deepy** [comment]
I might just have gotten bad test results, because if it works like I just described it feels like everything should be broken everywhere.

But there's still `noproxy` to deal with and we might still want to add a toggle for enabling proxy support in case anyone wants to do it manually instead.

**Comment by bsautel** [comment]
When you say in case of anyone wants to do it manually, you mean by configuring directly npm, for instance in the .npmrc file as explained [here](https://www.devtech101.com/2016/07/21/how-to-set-npm-proxy-settings-in-npmrc/)?

So I guess you learned that by testing our proxy code? 

There is something I don't understand: you say that Java does not let you specify if the proxy is HTTP or HTTPS, but there are two properties sets (`http.proxy*` and `https.proxy*`). You mean that `http` in the Java proxy does not correspond to the same use cases as `http` in the npm proxy?

**Comment by deepy** [comment]
Yeah, I think normally you'd either want to configure it yourself or have it auto-configured, probably not both.

for http/https, I misunderstood the Java SE documentation and the documentation we had internally at work seems incorrect, but with `noproxy` and a toggle this should be safe to release.

**Comment by bsautel** [comment]
Ok, I'll do these changes.

Where do we put the option that tells whether we should add automatically proxy configuration or not? In the `node` extension? And what is the default behavior?

I'll also add support to the `noproxy` case according to your recommendations above.

I'll also add some documentation to explain that we can support automatically support proxy options for `npm` and `yarn` not for `npx` that simply do not support proxies. And maybe put a link to the documentation that explains how to configure manually the proxy to use in the `.npmrc` file.

**Comment by deepy** [comment]
Hmm, can't think of a good parameter name, `useGradleProxySettings` is the best I can come up with, the default should be true

**Comment by bsautel** [comment]
I just pushed three commits that should solve this issue. Let me know if it corresponds to what you expected.

**Comment by deepy** [comment]
Looks great 👍
