### ISSUE TITLE
No value has been specified for property 'packageJsonFile'.

### ISSUE THREAD

**Issue by OrangeCrush** [node-gradle/gradle-node-plugin#85]
I'm seeing the following error when running `../gradlew npm_run_build`

```
* What went wrong:
A problem was found with the configuration of task ':UI:npmInstall'.
> No value has been specified for property 'packageJsonFile'.

```

The project in question uses gradle subprojects and I've added the following snippets to the subprojects build.gradle file to run the command `npm run build` from the `frontend/` directory  

```gradle
plugins {
    id "com.github.node-gradle.node" version "2.2.3"
}

node {
    nodeModulesDir = file('frontend/')
    version  = '12.16.1'
    download = true
    distBaseUrl = 'http://nodejs.org/dist'
    npmWorkDir = file('frontend/')
    workDir = file('frontend/')
}

jar.dependsOn npm_run_build
```

I found https://github.com/srs/gradle-node-plugin/issues/363 but I'm using gradle 4.10.  Not sure if this is related to that at all.

Am I just missing some configuration?

Thanks so much

**Comment by OrangeCrush** [comment]
Ok so I've had some learnings here..

The download and extract of node.js to the `workdir` deleted the source code (including `package.json`) when it was extracted to that directory.  Without a `package.json` present, I was seeing this error.

Thanks for picking up development on this plugin it's super useful

**Comment by camelpunch** [comment]
For any lost travellers: simply adding `nodeModulesDir` to the `node` block helped me to upgrade from the old srs fork (1.2.0 -> 2.2.4)

**Comment by Tyler-MDGL** [comment]
I am currently having the same issue within my build. I am using the web3j gradle plugin that plugin depends on the node gradle plugin. 

`
>./gradlew build

> Configure project :app
Project :app => no module-info.java found

> Task :app:npmInstall FAILED

>FAILURE: Build failed with an exception.

>* What went wrong:
>A problem was found with the configuration of task ':app:npmInstall' (type 'NpmInstallTask').
  >- In plugin 'com.github.gradle.node.NodePlugin' type 'com.github.gradle.node.npm.task.NpmInstallTask' property >'packageJsonFile' doesn't have a configured value.
    
 >   Reason: This property isn't marked as optional and no value has been configured.
    
   > Possible solutions:
     > 1. Assign a value to 'packageJsonFile'.
     >2. Mark property 'packageJsonFile' as optional.
    
    >Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#value_not_set for more details about this problem.
`

**Comment by nbruno** [comment]
I was able to resolve this by placing a `package.json` file at the project root, which is the directory I've configured for `node. nodeModulesDir`.

**Comment by KlausGrosser** [comment]
> I am currently having the same issue within my build. I am using the web3j gradle plugin that plugin depends on the node gradle plugin.
> 
> `
> 
> > ./gradlew build
> 
> > Configure project :app
> > Project :app => no module-info.java found
> 
> > Task :app:npmInstall FAILED
> 
> > FAILURE: Build failed with an exception.
> 
> > * What went wrong:
> >   A problem was found with the configuration of task ':app:npmInstall' (type 'NpmInstallTask').
> > 
> > 
> > * In plugin 'com.github.gradle.node.NodePlugin' type 'com.github.gradle.node.npm.task.NpmInstallTask' property >'packageJsonFile' doesn't have a configured value.
> 
> > Reason: This property isn't marked as optional and no value has been configured.
> 
> > Possible solutions:
> > > 1. Assign a value to 'packageJsonFile'.
> > >2. Mark property 'packageJsonFile' as optional.
> 
> ```
> >Please refer to https://docs.gradle.org/7.2/userguide/validation_problems.html#value_not_set for more details about this problem.
> ```
> 
> `

Could you solve this? I already tried to add the nodeModulesDir and it still not working

**Comment by deepy** [comment]
@KlausGrosser this didn't show up in my notifications since the issue is closed, but what's your use-case here?
To use only `node` but not `npm` or `yarn`?
I haven't seen any web3j sample projects where I can verify this and I'm not familiar with the setup, but if this uses `npm` or `yarn` you ought to have a `package.json`
