### ISSUE TITLE
Unable to override the methods in npm setuptask.groovy

### ISSUE THREAD

**Issue by sadheeshv** [node-gradle/gradle-node-plugin#86]
https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/kotlin/com/moowork/gradle/node/npm/NpmTask.kt

This class has open access but methods don't. I have a plugin wrapped on original gradle-node- plugin (https://github.com/srs/gradle-node-plugin)  which used work fine but broke when I upgrade to gradle 6.x. Hence I trying to use this plugin( from the forked repository), but unfortunately I couldn't override the method "exec" in the task. Would be nice if you could fix API and keep it as original. Thanks

**Comment by deepy** [comment]
Thank you for the report!
The latest published 2.x version of the plugin is of the Groovy version so in those it should still be possible to work as before

**Comment by sadheeshv** [comment]
Thanks. It works find with 2.2.3
