### ISSUE TITLE
Are ignoreExitValue and execOverrides properties relevant for NpmSetupTask and YarnSetupTask?

### ISSUE THREAD

**Issue by bsautel** [node-gradle/gradle-node-plugin#92]
I am wondering whether these properties are relevant. Those task are not generic ones like `NpmTask` that can be used for any usage, but they are designed for a specific `npm` or `yarn` command.

If we decide they are relevant, what about `workingDir` and `environment` that are also available on all the other tasks that have the `ignoreExitValue` and `execOverrides` properties?

I ask that now because we can now break backward compatibility if needed until 3.0 is released.

**Comment by deepy** [comment]
I think there might be a stronger case for `execOverrides` than `ignoreExitValue`, but I can't come up with any cases for either

**Comment by bsautel** [comment]
These tasks are a bit different from the other ones. We perfectly know the commands that they run and it should be our job to configure them in order to get them work.

I propose to follow this strategy: we remove these configuration properties and if someone reports us an issue corresponding to a missing configuration, we try to fix the issue directly in the task code instead of using these properties. And if it is really a specific use case, we will add them again. What do you think about that?

**Comment by bsautel** [comment]
These tasks are a bit different from the other ones. We perfectly know the commands that they run and it should be our job to configure them in order to get them work.

I propose to follow this strategy: we remove these configuration properties and if someone reports us an issue corresponding to a missing configuration, we try to fix the issue directly in the task code instead of using these properties. And if it is really a specific use case, we will add them again. What do you think about that?

**Comment by deepy** [comment]
Sounds good to me, the only use-case I can think of for `ignoreExitValue` can be replaced with `onlyIf` or similar

**Comment by bsautel** [comment]
Ok, that's done!
