### ISSUE TITLE
Should we use Node.js 14 by default?

### ISSUE THREAD

**Issue by bsautel** [node-gradle/gradle-node-plugin#94]
I just come to see that [Node.js 14 just comes to be published](https://medium.com/@nodejs/node-js-version-14-available-now-8170d384567e).

As we already broke backward compatibility with the future 3.0, shouldn't we use this new Node.js version by default?

Personnally, I think we should.

**Comment by deepy** [comment]
I'd say it makes more sense for us to use the latest LTS version which today seems to be 12.16.2, though it seems like support for 12.x as LTS is going to be dropped before 14.x so I'm not really sure what the benefits would be

**Comment by bsautel** [comment]
I did not notice that version 14 was not yet an LTS. In fact, [it will be starting from october](https://nodejs.org/en/about/releases/). So you are right, let's use the latest 12 version.
