### ISSUE TITLE
yarn task's node_modules output directory is declared twice in version 2.2.3

### ISSUE THREAD

**Issue by bsautel** [node-gradle/gradle-node-plugin#96]
The `node_modules` output directory is declared twice in the `yarn` task:
- Once as a file tree annotated `@OutputFiles`
- Once as a file tree or a directory according to the node modules output filter configuration

Up-to-date checking is much faster with directory than file trees, so we use a directory when it is possible and a file tree otherwise. But I forgot to remove the original file tree declaration and we now have both of them, and it slows down up-to-date checking.

**Comment by bsautel** [comment]
@deepy, I discovered this issue by doing [this experiment](https://github.com/node-gradle/gradle-node-plugin/issues/81#issuecomment-619804562).

Maybe we should publish a 2.2.4 version that fixes this issue. It will fasten `yarn` task up-to-date checking.

**Comment by deepy** [comment]
Sounds good to me, I'll just have a quick look and see if there's anything else declaring things multiple times

**Comment by deepy** [comment]
Looks good, but `getPackageLockFileAsInput`/`getPackageLockFileAsOutput` are starting to look more and more hilarious every time I see htem
