### ISSUE TITLE
Rename nodeModulesDir?

### ISSUE THREAD

**Issue by bsautel** [node-gradle/gradle-node-plugin#99]
When I was answering to #98, I realized that the `nodeModulesDir`'s property name can be confusing. It can let us think that this is the path of the `node_modules` directory whereas it is the path of the directory containing the `node_modules` directory. It also contains the `package.json` directory.

I think that we should rename it before we release the 3.0 version, if we do it later, we will have to support both the new name and the former name. What about `nodeProjectDir`?

**Comment by deepy** [comment]
Sounds great, but if we rename it we should add deprecated getter/setter for the old attribute so that a warning is triggered and the upgrade is less painful

**Comment by bsautel** [comment]
Ok, thanks, I am going to do that.

**Comment by anapsix** [comment]
FYI: using version `2.2.4`, when using `nodeProjectDir` instead of `nodeProjectDir` I'm getting an error
```
A problem occurred evaluating script.
> Could not set unknown property 'nodeProjectDir' for extension 'node' of type com.moowork.gradle.node.NodeExtension.
```

**Comment by bsautel** [comment]
This change was done in the 3.0 version that is not yet released. In the 2.2.4 version, the property to use is `nodeModulesDir`.
